### DISCUSSION TITLE
State is not showing

### DISCUSSION THREAD

**Discussion by stilldisturbing** [kalkih/mini-media-player#663] [Q&A]
Trying to us the mini-media-player to show my XBox consoles states and not allow the other functions.  It shows up, however I don't see the state that I do with the standard media player.  You can see the mini-media-player entity is missing the "Off" and the standard media player has the "Off" showing.

Not sure if I'm missing something or not.  Any thoughts?

![mini-media-player card](https://user-images.githubusercontent.com/7740589/167142921-02579a0b-917c-4c6a-8682-ab38b55babf9.png)

This is my entities card
```
type: entities
entities:
  - entity: media_player.projector_xbox
    type: custom:mini-media-player
    icon: mdi:microsoft-xbox
    group: true
    tap_action: none
    hide:
      volume: false
      power: true
      controls: true
      power_state: false
      icon_state: false
      state_label: false
  - entity: media_player.projector_xbox
    icon: mdi:microsoft-xbox
title: XBOX Consoles
state_color: true
```
