### DISCUSSION TITLE
Help with speaker_group configuration

### DISCUSSION THREAD

**Discussion by GizmoGoody** [kalkih/mini-media-player#673] [Q&A]
I have two echo devices which work great with mini-media-player directly and using Spotcast to call playlists, but I cannot seem to get their speaker groups configured properly. It renders properly in the UI, but when I select echo B under group management, I get "Failed to call service media_player/join. Entity media_player.echo_a does not support this service."

Since they're both on the same platform (media_player), shouldn't this work?

Here's my yaml:

```
      - title: Echo A
        type: custom:mini-media-player
        entity: media_player.echo_a
        hide:
          power: true
          icon: true
          source: true
        speaker_group:
          platform: media_player
          show_group_count: true
          entities:
            - entity_id: media_player.echo_a
              name: Echo A
            - entity_id: media_player.echo_b
              name: Echo B
```
