### DISCUSSION TITLE
idle view

### DISCUSSION THREAD

**Discussion by Steve-85** [kalkih/mini-media-player#681] [Q&A]
Hi,

How can I stop the card from hiding the volume controls when the media player isn't active? 
My current config is:

```
type: entities
entities:
  - type: custom:mini-media-player
    entity: media_player.kitchen_hifi
    name: Kitchen
    group: true
    idle_view:
      when_idle: false
      when_standby: false
      when_paused: false
```
