### DISCUSSION TITLE
Trigger scene from shortcut button?

### DISCUSSION THREAD

**Discussion by ge4me** [kalkih/mini-media-player#689] [Q&A]
Having trouble triggering a scene from a shortcut button.  Here is my shortcut config:

```
shortcuts:
      columns: 4
      buttons:
        - name: Top 50
          type: playlist
          id: spotify:user:[redacted]:playlist:37i9dQZEVXbLRQDuF5jeBp
          data:
            - action:
                service: scene.turn_on
                target:
                  entity_id: scene.turnondenon
```
