### DISCUSSION TITLE
How do I get Sonos and Homepds to Play Together?

### DISCUSSION THREAD

**Discussion by NR3Y** [kalkih/mini-media-player#762] [Q&A]
I have a combination of Sonos and Apple Homepod Minis around the house. The player works great with the Sonos stuff, but if I add in a Homepod, I can't get music to play on the Homepod. Perhaps I'm doing something really silly.

Code snippet:

```
 - type: custom:mini-media-player
    entity: media_player.laundry_room_sonos
    name: Laundry Room SONOS
    icon: phu:sonos-one
    artwork: none
    hide:
      power: true
      progress: true
      controls: true
    speaker_group:
      show_group_count: false
    group: false
  - type: custom:mini-media-player
    entity: media_player.darrells_homepod
    name: Darrell's Office HomePod
    artwork: none
    hide:
      power: true
      progress: true
      controls: true
    speaker_group:
      show_group_count: false
    group: false
```
