### DISCUSSION TITLE
Use Google for TTS

### DISCUSSION THREAD

**Discussion by Eisbaer2** [kalkih/mini-media-player#829] [Q&A]
How can I use Google as a TTS service?

I have a working automation in HA:

service: tts.speak
target:
  entity_id: tts.google_en_com
data:
  cache: true
  media_player_entity_id: media_player.squeezebox_radio
  message: TEXT
  language: de

Isn't it possible to use this service? I haven't found out how.

**Comment by remy** [comment]
I'm stuck on this too, this is my config:

```yaml
tts:
  platform: service
  data:
    service: tts.speak
    target:
      entity_id: tts.google_en_com
    service_data:
      cache: true
      media_player_entity_id: media_player.kitchen_speaker
    message_field: text
```

But I get the following error:

```
Failed to perform the action tts/speak. extra keys not allowed @ data['text]
```
