### DISCUSSION TITLE
Shortcut to Music Assistant folder/playlist

### DISCUSSION THREAD

**Discussion by LeiChat** [kalkih/mini-media-player#903] [Q&A]
Would appreciate any advice on how to configure a shortcut to a folder and/or playlist in Music Assistant (running locally as HA add-on), please.

Managed to get shortcuts for Sonos internet radio stations working. Sharing in case that's of use to others.

```
shortcuts:
  columns: 2
  label: Favourites
  list:
    - name: Classic FM
      type: music
      id: x-rincon-mp3radio://http://media-ice.musicradio.com/ClassicFMMP3
    - name: Heart Dance
      type: music
      id: x-rincon-mp3radio://http://media-ice.musicradio.com/HeartDanceMP3
    - name: Smooth Chill
      type: music
      id: x-rincon-mp3radio://http://icecast.thisisdax.com/SmoothChillMP3
```
