### ISSUE TITLE
Cover Artwork is reloading every few seconds

### ISSUE THREAD

**Issue by amp-man** [kalkih/mini-media-player#100]
I have the issue that the cover art reloads every few seconds or when pressing a button in the UI. This happens in Safari as well as Chrome.

![Image](https://media.giphy.com/media/9Pen33TMaKBSBi9Utw/giphy.gif)

Here is my lovelace configuration for that card:

```
entities:
  - artwork: cover
    entity: media_player.bad
    group: true
    hide: null
    power: true
    short_info: false
    show_progress: true
    type: 'custom:mini-media-player'
  - artwork: cover
    entity: media_player.terrasse
    group: true
    hide: null
    power: true
    short_info: false
    show_progress: true
    type: 'custom:mini-media-player'
show_empty: false
state_filter:
  - playing
  - paused
type: entity-filter
```
