### ISSUE TITLE
Power button shows "off" instead of power symbol

### ISSUE THREAD

**Issue by dilruacs** [kalkih/mini-media-player#101]
I am using version 1.0.3 with Home Assistant 0.90.1.

I have multiple mini-media-players grouped. My TV shows an icon (power symbol), 2 others have their power button hidden.
The last entity should show the power button, instead it just says "off" as text instead of an icon.

```yaml
      - type: entities
        entities:
        - type: custom:mini-media-player
          entity: media_player.panasonic_viera_tv
          group: true
          hide:
            controls: true
          toggle_power: false
        - type: custom:mini-media-player
          entity: media_player.kodi
          group: True
          artwork: cover
          replace_mute: stop
          hide:
            power: True
            volume: True
            name: True
        - type: custom:mini-media-player
          entity: media_player.my_fire_tv_stick
          group: true
          artwork: cover
          hide:
            power: True
            volume: True
            name: True
        - type: custom.mini-media-player
          entity: media_player.bdps3200
          group: True
```
