### ISSUE TITLE
Change from sonos: to speaker_group: makes group 

### ISSUE THREAD

**Issue by ronschaeffer** [kalkih/mini-media-player#106]
v1.0.4

I tried updating my configuration from sonos: to the new speaker_group: option with platform: sonos. When I do that, both the speaker group icon and the expanded group list (set to true in my config) disappear. Reverting the changes makes the group icon and expanded list re-appear.  See the screenshots below. I don't know if it's relevant, but I've got the mini-media-player card embedded in a custom vertical-stack-in-card card. I've included the complete "before" working config at the end just in case.

Just let me know if you need more info or testing. Thanks as always.

Before:
![image](https://user-images.githubusercontent.com/12379923/56128891-ca85ee80-5f78-11e9-9e7b-a5f51648cdbb.png)

After:
![image](https://user-images.githubusercontent.com/12379923/56128914-dbcefb00-5f78-11e9-90f4-56fefb8f94e2.png)

```
card:
  cards:
    - elements:
        - service: script.turn_on
          service_data:
            entity_id: script.call_sonos_diningroomtab_launch
          style:
            left: 16%
            top: 47%
          type: service-button
        - service: script.turn_on
          service_data:
            entity_id: script.sonos_play_whole_house
          style:
            left: 62%
            top: 47%
          type: service-button
        - service: script.turn_on
          service_data:
            entity_id: script.sonos_downstairs_only
          style:
            left: 78%
            top: 47%
          type: service-button
        - service: script.turn_on
          service_data:
            entity_id: script.sonos_pause_whole_house
          style:
            left: 92%
            top: 47%
          type: service-button
      image: /local/images/sonos_control_6.png
      type: picture-elements
    - artwork: cover
      entity: media_player.dining_room_2
      hide:
        icon: true
        power: true
        source: false
      sonos:
        entities:
          - entity_id: media_player.dining_room_2
            name: Dining Room
          - entity_id: media_player.living_room
            name: Living Room
          - entity_id: media_player.kitchen
            name: Kitchen
            volume_offset: 15
          - entity_id: media_player.guest_room_2
            name: Guest Room
          - entity_id: media_player.library
            name: Library
          - entity_id: media_player.master_bedroom_2
            name: Master Bedroom
          - entity_id: media_player.study
            name: Study
          - entity_id: media_player.garden
            name: Garden
            volume_offset: 43
        expanded: true
        show_group_count: true
        sync_volume: true
      type: 'custom:mini-media-player'
    - entities:
        - entity: switch.garden_sonos_2
          name: Garden Sonos Power
      show_header_toggle: false
      type: entities
  type: 'custom:vertical-stack-in-card'
style:
  '--paper-card-background-color': 'rgba(0, 0, 0, 0.0)'
type: 'custom:card-modder'
```
