### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by jasonkelly214** [kalkih/mini-media-player#109]
I just implemented 1.0.4 for Hassio 0.91.3 but I'm not seeing the progress bar at all. Am I doing something wrong? Everything else works fine, works as js and module.

**Comment by kalkih** [comment]
Hi,
What kind of media player are you using as the card entity?
The media player component has to support and expose the following attributes in order for the card to be able to calculate the progress (media_duration, media_position & media_position_updated_at).

**Comment by jasonkelly214** [comment]
Spotify. Here's what I'm seeing: [https://i.imgur.com/mUokHdO.jpg](url)

configuration for spotify:
```
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
```
