### ISSUE TITLE
Runtime misplacement

### ISSUE THREAD

**Issue by RomRider** [kalkih/mini-media-player#119]
Hey,

It appears that there's a slight glitch with the runtime placement (currently using Chrome both desktop and android). Also when the runtime is not displayed, the progress is kind of _dimmed_
* `hide.runtime: false`
![image](https://user-images.githubusercontent.com/21064206/57580917-21b3ac00-74b0-11e9-9d86-31f51a2d65ba.png)
* `hide.runtime: true`
![image](https://user-images.githubusercontent.com/21064206/57580966-db128180-74b0-11e9-9c68-6ca7ad9dfbe5.png)

Here's my config:
```yaml
      type: custom:mini-media-player
      entity: media_player.sonos_universal
      name: Sonos Connect
      artwork_border: true
      icon: mdi:disc-player
      hide:
        name: true
        icon: true
        power: true
        volume: false
        shuffle: false
        source: true
        progress: false
        runtime: false/true
      artwork: full-cover
      group: false
      max_volume: 80
```
