### ISSUE TITLE
[Feature Request] Keep volume buttons present regardless of state

### ISSUE THREAD

**Issue by Madseason41** [kalkih/mini-media-player#123]
I currently have two dumb TVs that I control via Broadlink Minis. Is there a way to keep the volume buttons (volume_stateless: true) active no matter the state? If my state is out of sync I would still like the ability to manipulate the volume without having to worry with correcting the state of the TV. Same with any other functions that disappear based on manipulating the power button.

Example
track_state: false.

All buttons remain and stay active no matter what state the media player card thinks the media player is in.

Also in regards to shortcuts, can they be used to make service calls or must those be rolled into scripts?

Ex. 
```
  service: androidtv.adb_command
  data:
    entity_id: media_player.androidtv_tv_living_room
    command: "HOME"
```
Use case for that would be to add a row or two of buttons for remote actions that might be needed, such as remote control direction use.

Thanks,
