### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by darkkatarsis** [kalkih/mini-media-player#127]
There is a problem when mini-media-player has as source virtual entity like "media_player.spotify" from https://github.com/hassio-addons/addon-spotify-connect, other media_player sources work fine

error from the dev console on chrome:

```
app.a259a502.js:2 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at HTMLElement._listenKeyEventListeners (app.a259a502.js:2)
    at HTMLElement.attached (app.a259a502.js:2)
    at HTMLElement.attached (app.a259a502.js:651)
    at HTMLElement.connectedCallback (app.a259a502.js:2)
    at Va._insert (mini-media-player-bundle.js?v=1.1.3:1)
    at Va._commitNode (mini-media-player-bundle.js?v=1.1.3:1)
    at Va._commitTemplateResult (mini-media-player-bundle.js?v=1.1.3:1)
    at Va.commit (mini-media-player-bundle.js?v=1.1.3:1)
    at db (mini-media-player-bundle.js?v=1.1.3:1)
```

**Comment by kalkih** [comment]
Hello, I'm not familiar with that particular addon.
Are you using the [spotify component](https://www.home-assistant.io/components/spotify/) and get the error when spotify has hass.io as source?

Could you post the attributes of the media player when you are seeing this issue, thanks.

Also, is that the entire error? there's no down arrow you can press to get a longer stack trace?

**Comment by darkkatarsis** [comment]
Thank you for the quick reply. Im using official hassio addon from https://github.com/hassio-addons/addon-spotify-connect (You can find it in the https://<HASSIO>:8123/hassio/store)

**lovelace.yaml**
```
type: vertical-stack
show_header_toggle: false
title: Music
cards:
  - type: 'custom:mini-media-player'
    entity: media_player.spotify
    group: false
    icon: 'mdi:spotify'
    shortcuts:
      columns: 3
      hide_when_off: true
      spotify_source:
        name: 'Source:'
        options:
          - option1
         - option2
```

error from console:
[https://ibb.co/YfxsVc8](url)
