### ISSUE TITLE
Add install/usage instructions for non yaml users

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-media-player#128]
Add install/usage instructions for non yaml mode users.

**Comment by IsaTTeN** [comment]
+1

I am using actually with lovelace, but I'm planning to move to UI Editor in the future, so could be a good idea.

**Comment by dk253** [comment]
Ummm how do i actually add this with hacs and the ui editor? I have used hacs to install but it does not show up as a control in the list in the ui editor.

**Comment by PorreKaj** [comment]
After clicking “configure UI” in the top right corner, click again an you now have a “raw config editor”

________________________________

**Comment by TheGreatBorg** [comment]
How do we none-yaml geeks get at chance to try this out? "Raw config editor" I see, but is there any useful guide for using "raw config editor" we can follow? I have tried the Fitbit page but that didn't work  at all (not for me). This Sonos grouping feature is what I'm seeking because Google Home will not do it (again I'm not that lucky or clever :-) )

**Comment by PorreKaj** [comment]
Not an expert, I just know that’s were to stick the references.

[Image]


________________________________

**Comment by dk253** [comment]
It took me a while to figure this out in HASSIO.  You have to click the three dots to see the Raw Editor menu then click it again.  Then I placed this at the top of the file:

```
resources:
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/button-card/button-card.js

```
This allowed me to add the modules down below like this:

```
  - badges: []
    cards:
      - type: entities
        entities:
          - type: 'custom:mini-media-player'
            entity: media_player.amp_living_room
            group: true
            hide:
              controls: true
          - type: 'custom:mini-media-player'
            entity: media_player.amp_kitchen
            group: true
            hide:
              controls: true

```
