### ISSUE TITLE
FEATURE REQUEST: Color Active Shortcut

### ISSUE THREAD

**Issue by JesseWebDotCom** [kalkih/mini-media-player#137]
Using shortcut ID and attribute, mini media player should know which shortcut is active.  I'd like to have the active button dynamically colored (like the power button).

Awesome component, keep up the good work.

**Comment by kalkih** [comment]
This is actually already a thing, it does however only work with attributes from the card entity itself, cam be useful for source, sound_mode, media_content_id and so on.
See [shortcuts object otpions](https://github.com/kalkih/mini-media-player#shortcuts-object).

Also works to display active item in the shortcuts list.

![hyperion_8123_lovelace_4 (1)](https://user-images.githubusercontent.com/457678/60387726-ded18600-9aa7-11e9-8639-35209bc05b51.png)


Example:
```yaml
shortcuts:
  attribute: source
  buttons:
    - name: Chromecast
      type: source
      id: Chromecast Kontor
  list:
    - name: Chromecast Kontor
      type: source
      id: Chromecast Kontor
```

**Comment by JesseWebDotCom** [comment]
Thanks but it's not working for me.

Lovelace:
```
                  buttons:
                    - id: http://listen.livestreamingservice.com/181-party_128k.mp3
                      name: Party
                      type: music                      
                      attribute: media_content_id
```

Entity attributes:
```
volume_level: 0
is_volume_muted: false
media_content_id: http://listen.livestreamingservice.com/181-party_128k.mp3
media_position: 0.745464
media_position_updated_at: 2019-06-29T21:31:32.738913+00:00
app_id: CC1AD845
app_name: Stream
friendly_name: Living Room
supported_features: 21391
media_content_type: music
entity_picture: /local/images/radio/originals/party.png
media_title: Party Radio
```

<img width="493" alt="Screen Shot 2019-06-29 at 5 37 13 PM" src="https://user-images.githubusercontent.com/20848952/60389695-9f4d6e80-9a94-11e9-81d8-1a69fe218774.png">
