### ISSUE TITLE
TTS Service not working for alexa

### ISSUE THREAD

**Issue by lweberru** [kalkih/mini-media-player#139]
Hi,

I have enabled the TTS interface for the mini mediaplayer, The device is an amazon echo. Which I am already using. The component works well, but the TTS service does not. I configured the following:

```
type: 'custom:mini-media-player'
entity: media_player.echo_bad
icon: 'mdi:spotify'
artwork: cover
tts:
  - platform: alexa
    type: tts
    entity_id: media_player.echo_bad
```
if I know test it, I get the following popup:

`
Error calling Service tts/undefined_say. Service not found.
`
So I think, that there is a mistake in getting the right name of the service.

Regards

**Comment by kalkih** [comment]
Hey,
The `tts` option is an object and not a list/array, remove the dash before `platform` and it should solve your issue 👍 
```yaml
tts:
  platform: alexa
  type: tts
```

Also, you don't have to specify `entity_id` if it's the card entity.
