### ISSUE TITLE
Capability to remove box-shadow

### ISSUE THREAD

**Issue by darkkatarsis** [kalkih/mini-media-player#140]
Is it possible to add the option to hide box-shadow style? I know there is a group option, but it also removes the padding that I want to keep.

**Comment by kalkih** [comment]
Hey, the box shadow is set by HA, you can use the theme variable `--ha-card-box-shadow` to change the box-shadow.
If you want to apply the box-shadow style to just a particular card, you should be able to use [lovelace-card-modder](https://github.com/thomasloven/lovelace-card-modder) and do:

```yaml
- type: custom:card-modder
  style:
    --ha-card-box-shadow: none
  card:
    - type: custom:mini-media-player
      ...
```
