### ISSUE TITLE
Media player icon state not set

### ISSUE THREAD

**Issue by ipodmusicman** [kalkih/mini-media-player#144]
Hi there, 

Just started using the mini player today and I don't know under which rock I had been hiding. :)

Just found some small issue.  I noticed that the "cast" icon is turned off on the player whereby it is turned on when you click to open the "more info" dialog box.  I also added the Nvidia Shield as a "non mini media player" to my entities card and the icon is turned "on".

See the image attached as well as the YAML code snippet below.

// this is using min media player.  Note the icon on the top left is "off"
  - entity: media_player.lounge_nvidia_shield
    group: true
    hide:
      power: true
      volume: true
    type: 'custom:mini-media-player'
  - entity: media_player.yamaha_receiver
    group: true
    hide:
      controls: true
      source: true
    type: 'custom:mini-media-player'
// this is not using mini media player.  Note the icon on the top left is "on"
  - entity: media_player.lounge_nvidia_shield

I'm using the Nvidia Shield as an example, but the same happens with the Yamaha AVR.

![image](https://user-images.githubusercontent.com/37892693/61171891-0fbcbb00-a57e-11e9-9f71-5c917b5ee2e7.png)

**Comment by kalkih** [comment]
Hello, thanks for the detailed explanation!

Yes, this is a feature that's not currently implemented in the card, but could be added eventually.
If you need this functionality right now you could try using [config-template-card](https://github.com/custom-cards/config-template-card) to make the icon change depending on state.

```yaml
# note: untested code
type: 'custom:config-template-card'
variables:
  - states['media_player.lounge_nvidia_shield'].state
card:
  type: custom:mini-media-player
  icon: "${vars[0] === 'off' || vars[0] === 'unavailable' ? 'mdi:cast' : 'mdi:cast-connected'}"
  ...
```

**Comment by ipodmusicman** [comment]
I thought it was a bug based on the default media player behavior.  I don't need it currently, but thought I'd log it to get it addressed to match the consistency of the default media player behavior.

**Comment by kalkih** [comment]
Entity icon color based on state is now supported, although disabled by default.

See the new `icon_state` option in the [hide option object](https://github.com/kalkih/mini-media-player#hide-object)

Enable icon state color:
```yaml
- type: custom:mini-media-player
  ...
  hide:
    icon_state: false
```

Thanks!
