### ISSUE TITLE
TTS with ga not working

### ISSUE THREAD

**Issue by Anothermetrial** [kalkih/mini-media-player#147]
Hi,
I receive the error "Failed to call service tts/undefined_say. Service not found.
lovelace editor:

entity: media_player.horia_s_bedroom_speaker
hide:
  volume: false
icon: 'mdi:google-home'
info: scroll
show tts: true
soundmode: full
source: icon
tts: 'platform:ga'
type: 'custom:mini-media-player'

added in config.yaml
notify:
  - name: ga_broadcast
    platform: rest
    resource: http://192.168.1.226:5000/broadcast_message

what am I doing wrong pls?

**Comment by kalkih** [comment]
Hey, hard to tell if you're config is correct or not when you don't post it inside a code block.
But seems like your tts card config object is invalid.

Here's an example of what it could look like:
```yaml
- type: custom:mini-media-player
  entity: media_player.example
  hide:
    icon: true
  tts:
    platform: ga
```
