### ISSUE TITLE
Show text of source select dropdown if there is enough space / configured

### ISSUE THREAD

**Issue by bernimoses** [kalkih/mini-media-player#149]
Hey, thanks for this nice card. It would be awesome if the source select appearance switches to `full` (dropdown with text) if `controls` and `volume` are hidden. Another option would be setting `source: full` to always be the dropdown with text. This is the config i tried (did not work):

```yaml
entity: media_player.tv
source: full
hide:
  controls: true
  volume: true
type: 'custom:mini-media-player'
```

![Screenshot from 2019-07-21 21-49-14](https://user-images.githubusercontent.com/239049/61596336-3627c980-ac02-11e9-8ab2-5942c64c1798.png)

What do you think?
