### ISSUE TITLE
Feature request: Soundtouch multiroom

### ISSUE THREAD

**Issue by mkoninkx** [kalkih/mini-media-player#155]
Hi!

I'm a big fan of your component! Thanks for all the time invested in it!
Would it be possible to integrate multiroom support for Bose Soundtouch speakers?
Behaviour would be the same as with Sonos.

Many thanks!
Br
Martijn

**Comment by kalkih** [comment]
Hello, Thanks.

Yes, from what I can tell after looking at the documentation it should be possible.

The service calls are not exactly the same as Sonos so would require some conditional statements, but def possible to implement.

**Comment by mkoninkx** [comment]
Hi Karl,

Great, thanks!
Let me know if you need a beta tester, I've got 3 soundtouch speakers setup in Home Assistant.

**Comment by da-anda** [comment]
I'd also be interested in it. Since you already seem to do some special casing for `sonos` related join/unjoin calls, would you be fine with doing the same for `soundtouch`? Alternatively it might be possible to make the core code more generic and build the service call structure out of some platform definitions which also could be overridden in the player config. Not sure how complicated such a "templating" kinda thing would be inside a lovelace component

**Comment by kalkih** [comment]
Adding an exception for the platform would probably be the way to go, similar to how we did with sonos before.
The sonos way now seems to be the "standard" way going forward with the format of `platform/action`.
See recent changes #161

Do you know if [`SOUNDTOUCH_ADD_ZONE_SLAVE`](https://www.home-assistant.io/components/soundtouch/#service-soundtouch_add_zone_slave) will create the group if it doesn't exist, similar to how [other platforms](https://www.home-assistant.io/components/sonos/#service-sonosjoin) does it?

**Comment by kalkih** [comment]
Hey, I've opened a PR with some initial code for the implementation #165.
Would be great if you guys could try it out. I've compiled a version of the PR branch that can be found [here (gist)](https://gist.github.com/kalkih/7f6161ca2e21cdbc66ac85cb6b9264e5).

Example config would look something like this:
```yaml
- type: custom:mini-media-player
  entity: media_player.office
  speaker_group:
    platform: soundtouch
    show_group_count: true
    entities:
      - entity_id: media_player.office
        name: Office
      - entity_id: media_player.livingroom
        name: Livingroom
      - entity_id: media_player.kitchen
        name: Kitchen
```

Thanks!
