### ISSUE TITLE
the source/sound_mode only show icon if in one line

### ISSUE THREAD

**Issue by fireinice** [kalkih/mini-media-player#162]
To integrate different parts of my home theater system, I hide almost all parts except source(or sound_mode). and it would only show the icon even I configuration source(or sound_mode) as full
```yaml
                  type: custom:mini-media-player
                  entity: media_player.optoma_uhd65
                  name: source
                  source: full
                  hide:
                    power: true
                    icon: true
                    volume: true
                    controls: true
```
