### ISSUE TITLE
Amazon Polly SSML

### ISSUE THREAD

**Issue by craigmcgowan** [kalkih/mini-media-player#197]
TTS does not work with Amazon Polly when using SSML.
The text which is entered, needs to have the <speak> tags wrapped around it

**Comment by kalkih** [comment]
Yes, SSML is not supported and will probably not be.
My suggestion would be to setup another amazon_polly component without ssml enabled and use that one for frontend stuff.

```yaml
tts:
  - platform: amazon_polly
    text_type: ssml
    aws_access_key_id: AWS_ACCESS_KEY_ID
    aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  - platform: amazon_polly_text
    aws_access_key_id: AWS_ACCESS_KEY_ID
    aws_secret_access_key: AWS_SECRET_ACCESS_KEY
```
