### ISSUE TITLE
Issue: Text to Speach input not using correct language

### ISSUE THREAD

**Issue by AnthonMS** [kalkih/mini-media-player#198]
When I use the text to speach input field, it uses english, when I have the component set for danish. The service works fine, I can call it from automations or use the service tab and it works fine and says it in danish. But when I use the frontend, it says it in english. 

I am not sure if it is a mini-media-player bug or what, but the component works fine, only when I call it from the text to speach input field.

**Comment by kalkih** [comment]
Hello,
I'm not able to reproduce this (only tried with google_translate since that's the only tts I've set up).
What service are you using and what does your card config and tts component config look like?

**Comment by AnthonMS** [comment]
Card Config:
`
          - type: custom:mini-media-player
            entity: media_player.anthon_s_vaerelse
            name: Google Home
            icon: mdi:google-home
            hide:
              power_state: false
            shortcuts:
              columns: 4
              buttons:
                - name: P1
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A03H.mp3
                - name: P3
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A05H.mp3
                - name: P6
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A29H.mp3
                - icon: mdi:radio
                  name: Afspil Radio
                  type: script
                  id: script.play_radio
                - name: Nova
                  type: music
                  id: http://live-bauerdk.sharp-stream.com/nova128.mp3
                - name: The Voice
                  type: music
                  id: http://live-bauerdk.sharp-stream.com/voice128.mp3
`

tts config:
`
tts:
  - platform: google_translate
    language: 'da'
`

**Comment by AnthonMS** [comment]
Card Config:
```
          - type: custom:mini-media-player
            entity: media_player.anthon_s_vaerelse
            name: Google Home
            icon: mdi:google-home
            hide:
              power_state: false
            shortcuts:
              columns: 4
              buttons:
                - name: P1
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A03H.mp3
                - name: P3
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A05H.mp3
                - name: P6
                  type: music
                  id: http://live-icy.gss.dr.dk/A/A29H.mp3
                - icon: mdi:radio
                  name: Afspil Radio
                  type: script
                  id: script.play_radio
                - name: Nova
                  type: music
                  id: http://live-bauerdk.sharp-stream.com/nova128.mp3
                - name: The Voice
                  type: music
                  id: http://live-bauerdk.sharp-stream.com/voice128.mp3
```

tts config:
```
tts:
  - platform: google_translate
    language: 'da'
```

**Comment by kalkih** [comment]
I don't see you using the cards tts option? or are you using the tts input in the more-info popup?

**Comment by AnthonMS** [comment]
If I add 
```
tts: true
```
It shows this error in the bottom when I press send: Could not connect to tts/undefined_say service. Service not found.

**Comment by kalkih** [comment]
The tts option takes an object as attribute.
See the [tts option object](https://github.com/kalkih/mini-media-player#tts-object)
```yaml
# example
- type: custom:mini-media-player
  entity: ...
  tts:
    platform: google_translate
```
