### ISSUE TITLE
Custom element doesn't exist: mini-media-player after git pull

### ISSUE THREAD

**Issue by snizzleorg** [kalkih/mini-media-player#20]
I updated the mini-media player and now I get 

```
Custom element doesn't exist: mini-media-player.

```

I have: 

```
resources:
  - url: /local/mini-media-player/mini-media-player.js
    type: module

```

and 

```
      - type: entities
        title: Media
        entities:
        - type: custom:mini-media-player
          entity: media_player.mpd
          #name: Media
          group: true
          show_source: true
        - type: custom:mini-media-player
          entity: media_player.kitchen
          name: Küche
          artwork: cover
          group: true
          hide_info: true
          # hide_power: true
          # hide_volume: true
          # show_source: true
          hide_controls: true

```

anything wrong with that? I also cleared the cache but still no luck.

I can access:

```
http://<hassip>:8123/local/mini-media-player/mini-media-player.js

```

so it should be all good...
