### ISSUE TITLE
Feature Request: Hide when unavailable

### ISSUE THREAD

**Issue by bagobones** [kalkih/mini-media-player#202]
For media players like plex it is nice to show what is playing but if the app is closed the state becomes unavailable.

It would be nice to completely hide the card when unavailable, or maybe even with paused or other states.

**Comment by kalkih** [comment]
Hello,
I think the [conditional card](https://www.home-assistant.io/lovelace/conditional/) is a perfect solution for this.

An example: (this will only display the card if the entity state is "playing")
```yaml
- type: conditional
  conditions:
    - entity: media_player.example
      state: playing
  card:
    entity: media_player.example
    type: custom:mini-media-player
    ...
```

You could add more conditions if you also want to show it when it's paused e.t.c.
