### ISSUE TITLE
Allow Template for Shortcut name

### ISSUE THREAD

**Issue by wbilger** [kalkih/mini-media-player#205]
Feature Request
As title says, would be amazing to be able to use temaplate values for shortcut  names, would be handy in the case of station presets that change.
ie.
- name: '{{ states.input_text.kitchen_radio_station_p1_text.state }}'

**Comment by kalkih** [comment]
Hello, thanks for your suggestion.

This won't be implemented, I understand the use-case and it would be neat but it's out of scope for the focus of this project. I always recommend going with the custom button-card for more advanced use cases.

With a config like this, you basically have the same card but with much more flexibility/customizability shortcuts/buttons:
![05|451x181](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/f/3/f3d089fcff0d2aceac1f3b2e059ed3711d13e7a5.png) 

```yaml
- type: custom:vertical-stack-in-card
  cards:
    - type: custom:mini-media-player
      entity: media_player.example
      ...
    - type: horizontal-stack
      cards:
      - type: custom:button-card
        ...
      - type: custom:button-card
        ...
      - type: custom:button-card
        ...
```

You could also utilize [config-template-card](https://github.com/iantrich/config-template-card) to make the mmp shortcuts templateable.
