### ISSUE TITLE
PS4 as media player

### ISSUE THREAD

**Issue by pegatron89** [kalkih/mini-media-player#208]
Hello,

Thanks for the card works great. I currently have it set up with my PS4 using shortcuts and "Hide_when_off: True".. I get the following:

![image](https://user-images.githubusercontent.com/32884978/71516645-08763900-28a2-11ea-8692-805f81f3d5b4.png)

My issue is, The hide_when_true works everywhere else except the PS4. I think it may be due to the playstations state being "standby" rather than "off" 

Love lace config:

```
  - entity: media_player.playstation_4
    hide:
      controls: true
      source: true
      volume: true
    icon: 'mdi:playstation'
    shortcuts:
      buttons:
        - icon: 'mdi:cowboy'
          id: ''
          type: playlist
        - icon: 'mdi:emoticon-dead-outline'
          id: ''
          type: playlist
        - icon: 'mdi:soccer'
          id: ''
          type: playlist
        - icon: 'mdi:gamepad-square-outline'
          id: ''
          type: playlist
      columns: 4
      hide_when_off: true
    type: 'custom:mini-media-player'
```
The shortcuts haven't been completely set up yet so i know they wont do anything. Would just be nice for them to be hidden when the ps4 is in rest mode / Standby

**Comment by kalkih** [comment]
Hello!
Yes you are correct, this is most likely because its state is reported as `standby` and not `off`.
If you add the following to your config (the `idle_view` option), it should solve it, give it a shot!

```yaml
- type: 'custom:mini-media-player'
  ...rest of config
  idle_view:
    when_standby: true
```

This will basically treat `standby` as `off`.
