### ISSUE TITLE
Custom Artwork

### ISSUE THREAD

**Issue by roblandry** [kalkih/mini-media-player#222]
I am using this card with many media players. Not all of them supply an artwork image. It would be great if there were a way to change the artwork based on source.

For instance, android tv will display Hulu (as the source) when playing. However, no artwork is supplied so its just the default background. I would like to display a hulu background. Likewise, when in netflix, a netflix artwork would be supplied.

Something like custom images stored in the www folder. and a config option for source -> image.

**Comment by kalkih** [comment]
Hello,
You can achieve this by utilising [config-template-card](https://github.com/iantrich/config-template-card), together with the card option `background`.

**Comment by roblandry** [comment]
Would it be possible to provide an example?

**Comment by kalkih** [comment]
Possibly something like this (untested):
```yaml
type: "custom:config-template-card"
variables:
  - states['media_player.example'].attributes.source
entities:
  - media_player.example
card:
  type: custom:mini-media-player
  background: "${if(vars[0] === 'netflix') { return '/local/netflix.png' }; else if(vars[0] === 'spotify') { return '/local/netflix.png' }; }"  
```
Unsure how it handles statements over multiple rows but if it does you could make it look a lot cleaner.
