### ISSUE TITLE
navigate tap_action does not work

### ISSUE THREAD

**Issue by mikey60** [kalkih/mini-media-player#231]
There is no response when I tap/click the All Music player. Actually I get no response when I tap/click the Al Music player if I only add the tap_action: true line in the same position.  I get the normal on/off time line when I click the family room audio cast player.  I have tried using the url action with the full path and clearing the cache on my browser with no success.
I am using the following versions with the card code shown below. 
mini-media-player version 1.6.0
Home Assistant version 0.105.5

```entities:
  - entity: media_player.all_music
    group: true
    hide:
      power: true
      source: true
      volume: true
    info: scroll
    tap_action: true
    action: navigate
    navigation_path: /lovelace/4/
    scale: 1.2
    source: icon
    type: 'custom:mini-media-player'
  - entity: media_player.family_room_audio_cast
    group: true
    hide:
      controls: true
      info: true
      power_state: false
    type: 'custom:mini-media-player'
type: entities
```

**Comment by kalkih** [comment]
Your config is invalid, tap_action takes an object as described in the docs.
Your config should look like this

```yaml
  - entity: media_player.all_music
    group: true
    hide:
      power: true
      source: true
      volume: true
    info: scroll
    tap_action:
      action: navigate
      navigation_path: /lovelace/4/
    scale: 1.2
    source: icon
    type: 'custom:mini-media-player'
```
