### ISSUE TITLE
Shortcut Image Size

### ISSUE THREAD

**Issue by broyuken** [kalkih/mini-media-player#236]
I'm trying to set shortcuts to albums/playlists but I wanted to have large icons so you could actually see the cover art to click on. I have the following set up, but the image that is displayed is tiny, about 25 x 25. Is there a way this could be customizable, or at least fit the column height that is configured?

```
        shortcuts:
          buttons:
            - id: 'spotify:artist:3yKoHgjtyenCOIRaD2Gghu'
              image: https://i.pinimg.com/originals/3a/f0/e5/3af0e55ea66ea69e35145fb108b4a636.jpg 
              type: playlist
            - icon: 'mdi:cat'
              id: Kitchen Echo Show
              type: source
          column_height: 200
          columns: 5
```
