### ISSUE TITLE
Add button with URL

### ISSUE THREAD

**Issue by pepeEL** [kalkih/mini-media-player#238]
Hi
Is any chance to add to this card button which run specific URL like this:

http://192.168.33.33/goform/formiPhoneAppDirect.xml?RCKSK0410741

I want add button to control my Denon AVR.... Thanks for help

**Comment by kalkih** [comment]
Hello, you can achieve this by setting up a [rest command](https://www.home-assistant.io/integrations/rest_command/) and call it by it's service from the button.

**Comment by pepeEL** [comment]
But how add it to your card ? Please help me by show example.... Please

**Comment by kalkih** [comment]
When you've setup the rest command just call it through its service in thee button shortcut
```yaml
...card config
  shortcuts:
    buttons:
      - name: Example
        type: service
        id: rest_command.example
```
