### ISSUE TITLE
Feature request: set info from shortcut

### ISSUE THREAD

**Issue by hindsholm** [kalkih/mini-media-player#239]
I use mini-media-player to control some Chromecast Audio devices and it works just fine :)
But for one of the players I have shortcuts to a number of radio channels with corresponding URLs and when Chromecast plays a URL directly, the app name is displayed as "Default Media Player" (or something similar), which is not very informative. Right now I just hide the `info` dynamically when the current media has no title by using a `template-config-card`, but it would be better to be able to override the `info` from the shortcut.
This is my current config:
```yaml
type: 'custom:config-template-card'
entities:
  - media_player.kokken
card:
  type: custom:mini-media-player
  entity: media_player.kokken
  artwork: cover
  hide:
    info: "${states['media_player.kokken'].attributes.media_title ? false : true}"
    power: true
  icon: mdi:cast-audio
  shortcuts:
    attribute: media_content_id
    columns: 6
    buttons:
      - icon: mdi:numeric-1-circle-outline
        type: music
        id: http://live-icy.gslb01.dr.dk/A/A03H.mp3
      - icon: mdi:numeric-3-circle-outline
        type: music
        id: http://live-icy.gslb01.dr.dk/A/A05H.mp3
      - icon: mdi:numeric-4-circle-outline
        type: music
        id: http://live-icy.gslb01.dr.dk/A/A10H.mp3
...
```
And this is how I imagine it could look:
```yaml
type: custom:mini-media-player
entity: media_player.kokken
artwork: cover
hide:
  power: true
icon: mdi:cast-audio
shortcuts:
  attribute: media_content_id
  columns: 6
  buttons:
    - icon: mdi:numeric-1-circle-outline
      type: music
      id: http://live-icy.gslb01.dr.dk/A/A03H.mp3
      info: Danmarks Radio P1
    - icon: mdi:numeric-3-circle-outline
      type: music
      id: http://live-icy.gslb01.dr.dk/A/A05H.mp3
      info: Danmarks Radio P3
    - icon: mdi:numeric-4-circle-outline
      type: music
      id: http://live-icy.gslb01.dr.dk/A/A10H.mp3
      info: Danmarks Radio P4
...
```
What do you think?
