### ISSUE TITLE
Media controls has max width of 200 even if nothing else on line

### ISSUE THREAD

**Issue by libots** [kalkih/mini-media-player#243]
I'm trying to use mini media player in a couple places to control _only_ the volume and mute on/off of a media player. When I do this, the mmp-media-controls element has a max-width of 200px. This works for when there are other things on that line, but since I've got everything else hidden, it looks pretty weird:

![2020-03-14](https://user-images.githubusercontent.com/989623/76687209-2a0cd400-65f8-11ea-8446-b2242cd3cbde.png)

Code is:
```
type: custom:mini-media-player
entity: media_player.receiver_lvrm
hide:
  icon: true
  name: true
  source: true
  power: true
  play_pause: true
  controls: true
```
