### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by nrgbistro** [kalkih/mini-media-player#254]
When I click the shortcuts button, nothing happens. Play/pause, next and previous track, and volume work fine. Here is my card configuration: 
```
artwork: cover
entity: media_player.downstairs
hide:
  power: true
icon: 'mdi:spotify'
shortcuts:
  buttons:
    - id: 'spotify:playlist:0vvXsWCC9xrXsKd4FyS8kM'
      name: LoFi Hip Hop
      type: playlist
    - icon: 'mdi:saxophone'
      id: 'spotify:playlist:6g9DvA0J2xDYcOiNNIJaT6'
      type: playlist
    - icon: 'mdi:dog'
      id: script.script_name
      type: script
    - data:
        entity_id: media_player.downstairs
        uri: 'spotify:playlist:37i9dQZF1DX9XiAcF7t1s5'
      id: spotcast.start
      name: Crooners Playlist
      type: service
  columns: 3
type: 'custom:mini-media-player'
```
My media setup is a few Amazon Echos connected through multiroom group in the Amazon Alexa app. The spotcast.start shortcut also does not work. After about 10 seconds it says: `Failed to called Spotcast/start: could not find device with name 'Downstairs'`, even though in devices my multiroom group from the Amazon Alexa integration is clearly called "downstairs".
