### ISSUE TITLE
Color "Source" shortcut buttons dynamically

### ISSUE THREAD

**Issue by dtreichler** [kalkih/mini-media-player#255]
It would be great if there was an option to make shortcut buttons that are `type: source` have the option of rendering dynamically depending whether or not that source is selected.

For example, in this card:

```yml
entity: media_player.kitchen_speakers
hide:
  controls: true
  icon: true
  power_state: false
  source: true
shortcuts:
  buttons:
    - icon: 'mdi:google-chrome'
      id: Chromecast
      type: source
    - icon: 'mdi:record-player'
      id: Record Player
      type: source
    - icon: 'mdi:television'
      id: TV
      type: source
    - icon: 'mdi:laptop'
      id: Office
      type: source
  columns: 4
  hide_when_off: true
type: 'custom:mini-media-player'
```

when the source for `kitchen_speakers` is `Chromecast`, I'd like to make it so the icon is colored (sort of like how the `hide:power_state` option works today).
