### ISSUE TITLE
Feature Request: Automatically naming Bose Soundtouch presets in Shortcuts

### ISSUE THREAD

**Issue by schneekluth** [kalkih/mini-media-player#284]
Hello @kalkih,

first of all thank you for implementing multi room features for the Bose Soundtouch integration. Great feature.

I use 4 Soundtouch devices with the shortcuts settings to quickly start playing predefined playlists:

![image](https://user-images.githubusercontent.com/5740913/79209432-b868b580-7e43-11ea-8ae4-ed92e660970a.png)

These shortcuts are also exposed by the speakers API when you call `http://IP_OF_SPEAKER/presets` and they have the name and even an URL to the cover art in it:

![bose_api](https://user-images.githubusercontent.com/5740913/79210300-e69ac500-7e44-11ea-8949-f7792aa844d7.png)

Would it be possible for mini-media-player to read and display the names of the presets automatically? Maybe even use the cover art in a shortcut button?

I am asking because I don't use `lovelace.yaml` mode in hass and have to edit these presets 4 times in the GUI. It would be a handy feature if the presets change automatically.

**Comment by kalkih** [comment]
Hey,
Glad you like the group management feature!

Unfortunately not going to implement this one, it would be a platform specific feature, and I try to stay away from adding those.

Would indeed be a cool feature though, feel free to fork this card and extend it as you like with e.g. platform specific features like this, I'm sure more people would be interested in this as well, could become "mini-bose-player" 😉

**Comment by jpearce73** [comment]
What about a method that can be called to update a button's text?
Then people can write their own automation to push the information across

**Comment by kalkih** [comment]
Please elaborate, how would that work?
I don't really get what you mean by calling a method, this card is just a frontend and has no "persistent state", it doesn't function like components/integrations which usually expose service calls and store data.

You should be able to achieve something similar with the help of [config-template-card)](https://github.com/iantrich/config-template-card) though.

**Comment by jpearce73** [comment]
I am thinking that a button could be given a content string and expanded like a template or the markdown card
https://www.home-assistant.io/lovelace/markdown/

Then you could pull the state or an attribute off an entity you create or have a media platform (such as soundtouch) export the text for the 6 buttons as a property to include in the markdown.

**Comment by schneekluth** [comment]
I like the idea of @jpearce73. What about you @da-anda? I am sure you have enough of homeassistant pull requests but maybe you have an idea. Unfortunately I cannot code at all but if there is anything else when it comes to testing stuff I am glad to help out. Maybe one could integrate the currently stored presets in the attributes of each player?

**Comment by kalkih** [comment]
> I am thinking that a button could be given a content string and expanded like a template or the markdown card

You can already do that with the help of config template card. I don't really want to add templating to the card as there are solutions that solves that problem just fine already.

**Comment by jpearce73** [comment]
I agree with Kalkih.
Duplicating functionality that exists elsewhere is a bad idea (unless its prohibitively difficult to use).
We should look into the template card and try to use that to solve the problem, maybe contribute an example back to Kalkih can add it to the documentation page.

Maybe start by sharing your lovelace yaml for the sound touch here and I can try and help you.

**Comment by schneekluth** [comment]
Here is the yaml file for the media player shown in the screenshot in first post:

```yaml
type: 'custom:mini-media-player'
artwork: full-cover-fit
entity: media_player.soundtouch_room2
group: true
hide:
  shuffle: true
  source: false
  volume: false
icon: 'mdi:speaker-wireless'
name: Bose Room2
power_color: true
shortcuts:
  column_height: 30
  align_text: left
  buttons:
    - icon: 'mdi:numeric-1-box'
      id: 1
      name: Deepmix Moscow
      type: playlist
    - icon: 'mdi:numeric-2-box'
      id: 2
      name: I can haz We3kend?
      type: playlist
    - icon: 'mdi:numeric-3-box'
      id: 3
      name: Anrüchige Frauen
      type: playlist
    - icon: 'mdi:numeric-4-box'
      id: 4
      name: Tagesschau 100s
      type: playlist
    - icon: 'mdi:numeric-5-box'
      id: 5
      name: Mix der Woche
      type: playlist
    - icon: 'mdi:numeric-6-box'
      id: 6
      name: Autobahn bei Nacht
      type: playlist
```

**Comment by jpearce73** [comment]
OK this is a proof of concept

Using the config-template-card we can put attributes from media_player.soundtouch (or any other platform) into our button names. And they update as the attribute changes.

![image](https://user-images.githubusercontent.com/19938737/79586102-99c72080-80c8-11ea-93e9-4b20f9986322.png)

=> So to get the final solution you are seeking I will need to enhance the soundtouch library and add exported attributes for the button presets and then those could be used in the template.

Give me a bit of time for that... but I like the idea of it too.

**Comment by jpearce73** [comment]
Please try this solution.
Install this upgraded soundtouch integration into your /config/custom_components folder. This will export the preset button information.

[soundtouch.zip](https://github.com/kalkih/mini-media-player/files/4500277/soundtouch.zip)

Install by using the add-on terminal
1. copy soundtouch.zip to your /config folder
2. mkdir custom_components
3. cd custom_components
4. tar xzvf ../soundtouch.zip

Then use lovelace code like this to put a mini-media-card inside a config-template-card. Note the expansion of the newly exported soundtouch_presets attribute.

```
card:
  entity: media_player.soundtouch_kitchen
  shortcuts:
    align_text: left
    buttons:
      - icon: 'mdi:numeric-1-box'
        id: 1
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[0]}
        type: playlist
      - icon: 'mdi:numeric-2-box'
        id: 2
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[1]}
        type: playlist
      - icon: 'mdi:numeric-3-box'
        id: 3
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[2]}
        type: playlist
      - icon: 'mdi:numeric-4-box'
        id: 4
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[3]}
        type: playlist
      - icon: 'mdi:numeric-5-box'
        id: 5
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[4]}
        type: playlist
      - icon: 'mdi:numeric-6-box'
        id: 6
        name: >-
          ${states['media_player.soundtouch_kitchen'].attributes.soundtouch_presets[5]}
        type: playlist
  type: 'custom:mini-media-player'
entities:
  - media_player.soundtouch_kitchen
name: Templated SoundTouch
type: 'custom:config-template-card'

```
