### ISSUE TITLE
Icons missing in HA 0.110.beta

### ISSUE THREAD

**Issue by mgiako** [kalkih/mini-media-player#302]
Since I installed the latest HA beta (0.110.0b3) my mediaplayers don't show the icons anymore.
The commands in more-info window works, but in lovelace the icons are missing.
Not only the "automatic icons" (Power, play,next stop ecc.), but also the ones in the custom shortcuts.
It's only me?

**Comment by kalkih** [comment]
Hello, this was fixed in the latest release https://github.com/kalkih/mini-media-player/pull/301

**Comment by mgiako** [comment]
@kalkih sorry,I had a problem and not really on 1.8.0, but...

even now, the normal icons are back, but the shortcut icons not:

![image](https://user-images.githubusercontent.com/44270368/82217268-7c30e500-991a-11ea-99fc-dc5d49772538.png)

this is my config:
```
         - type: custom:mini-media-player
            entity: media_player.tvsala
            volume_stateless: true
            source: full
            hide:
              power: true            
            shortcuts:
               columns: 5 # Max buttons per row
               buttons:
                 - icon: mdi:power
                   type: service
                   id: script.turn_on
                   data:
                     entity_id: script.toggletv
                 - name: INFO
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: info
                 - name: TV
                   type: source
                   id: DTV
                 - name: PC
                   type: source
                   id: HDMI 1
                 - name: Playst
                   type: source
                   id: HDMI 2

                 - icon: mdi:play
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: play
                 - icon: mdi:pause
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: pause
                 - icon: mdi:stop
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: stop
                 - icon: mdi:fast-forward
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: ffwd
                 - icon: mdi:record-rec
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: record
```
