### ISSUE TITLE
card not working on lates version of home-assistant

### ISSUE THREAD

**Issue by gbdavidx** [kalkih/mini-media-player#311]
lSSUE...

local/mini-media-player-bundle.js?v=1.8.1 i have this and it is in my resources and i can view the javascript on my browser

VERSION....
Home Assistant 0.110.1
Path to configuration.yaml: /config

Developed by a bunch of awesome people.

Published under the Apache 2.0 license
Source: server — frontend-ui

Built using Python 3, Polymer, Icons by Google and MaterialDesignIcons.com.

Frontend version: 20200519.1 - latest

Part of my code..., is it a user error?
```

title: My Awesome Home
views:
  - title: Home

    cards:
    - cards:
        - type: thermostat
          entity: climate.downstairs 
        - type: thermostat
          entity: climate.main_floor 
      type: horizontal-stack

    - cards:
      type: custom:vertical-stack-in-card
      cards:
        - type: entities
          title: Harmony
          entities:
            - type: section 
              style: |
                .divider { display: none; }
                .label { margin-top: 0; }
            - entity: switch.appletv
              image: /local/images/logos/remote.png
              name: Watch TV
       # - type: weather-forecast
       #   entity: weather.home
      type: vertical-stack
    - cards:
        - cards:
            - type: light
              entity: light.tv_light_1
            - type: light
              entity: light.tv_light_2
          type: horizontal-stack
        - cards:
            - type: light
              entity:  light.desk_light
            - type: light
              entity: light.living_room_light
          type: horizontal-stack
        - cards:
            - type: custom:mini-media-player
              entity: media_player.media_player.beiler_s_2nd_echo_dot
              icon: mdi:spotify
              artwork: cover
          type: horizontal-stack
      type: vertical-stack

```
No cards are loading... :(. it should be underneath my light switches

<img width="683" alt="Screen Shot 2020-05-23 at 9 18 28 PM" src="https://user-images.githubusercontent.com/26369204/82745579-f4dcda80-9d3a-11ea-949c-a08e7b90f072.png">
