### ISSUE TITLE
mini-media-player + playlist?

### ISSUE THREAD

**Issue by Emphantom4d** [kalkih/mini-media-player#324]
Hey. I don’t understand how to make a playlist of my music?
I made an online radio. but I also want to listen to my music.
made through a script

`title: Home Assistant
views:
  - title: Главная
    id: main
    icon: mdi:home-assistant
    
  - title: Медиа
    icon: mdi:google-home
    cards: 
      - type: custom:mini-media-player
        entity: media_player.nest
        background: ""
        artwork: cover
        source: icon
        hide:
         volume: false
        shortcuts:
          columns: 4 #Max buttons per row
          buttons: 
        # Start predefined playlist
          - icon: #mdi:radio-am
            name: Наше Радио
            type: script
            id: script.1590868868709`

**Comment by kalkih** [comment]
Hello, to call a script from a button see [this example](https://github.com/kalkih/mini-media-player#card-with-media-shortcuts)

```yaml
- entity: media_player.spotify
   type: custom:mini-media-player
   shortcuts:
     buttons:
       - icon: mdi:dog
         type: script
         id: script.script_name
```
