### ISSUE TITLE
Is there a way to define shortcuts once and use the for each instance in UI?

### ISSUE THREAD

**Issue by u8915055** [kalkih/mini-media-player#336]
hello,  I absolutely love this module.  So clean and configurable.  However I had a question.  I have a set of common shortcuts that I want to have available for each media player.  Instead of defining these for each media player entity, is there a way to define them once and use that definition for each player?  Im hoping there's an easy way to do this.  Im using yaml mode for my config.  Thank you in advance.

**Comment by u8915055** [comment]
I think I solved my own problem.  Using YAML anchors I seem to have been able to make this work.  In the top of my lovelace-ui.yaml file I defined the following as an example
```
media_shortcuts: &media_shortcuts
  buttons: 
    - name: abc
      type: source
      id: abc_id
    - name: def
      type: music
      id: aac://http://34.83.211.194/ppm-jazz24aac256-ibc1?session-id=a4ea7caa0bb0957b05476d7ced33cefd&source=TuneIn
    - name: ghi
      type: source
      id: ghi_id
    - name: jkl
      type: source
      id: jkl_id
```
then further down in my yaml file I have this:

```
          - type: custom:mini-media-player
            entity: media_player.sonos_master_bedroom
            icon: "custom:ha-sonos"
            artwork: cover
            volume_stateless: true
            source: icon
            idle_view:
              when_idle: true
              when_paused: true
              when_standby: true
            hide:
              power: true
            name: Sonos
            shortcuts:
              columns: 2
              << : *media_shortcuts
```

Hope this helps others.
