### ISSUE TITLE
Feature request: hide players when state is "Unavailable"

### ISSUE THREAD

**Issue by fredrike** [kalkih/mini-media-player#34]
When grouping multiple players some of them are shown as `unavailable`, it would be nice if they could be hidden..

**Comment by kalkih** [comment]
There are two cards in core HA that potentially could solve this for your use case.

The first one is the [Conditional card](https://www.home-assistant.io/lovelace/conditional/).
Config would look something like this:
```yaml
- type: conditional
  conditions:
    - entity: media_player.chromecast_sovrum
      state_not: unavailable
  card:
    entity: media_player.chromecast_sovrum
    type: custom:mini-media-player
```

And then there's the [Entity filter card](https://www.home-assistant.io/lovelace/entity-filter/).
This should work better if you are grouping cards, requires some additional parameters though:

```yaml
- type: entity-filter
  state_filter:
    - on
    - off
    - playing
    - paused
    - idle
  entities:
    - entity: media_player.chromecast_sovrum
      type: custom:mini-media-player
      group: true
    - entity: media_player.chromecast_vardagsrum
      type: custom:mini-media-player
      group: true
    - entity: media_player.chromecast_badrum
      type: custom:mini-media-player
      group: true
```

Would be great if one of these solutions would do the job since they are universal and already a part of core HA, let me know. 🙂
