### ISSUE TITLE
shortcut image size does not increase when increasing column height

### ISSUE THREAD

**Issue by theone11** [kalkih/mini-media-player#348]
Using v1.9.1

I want image size to increase when column height increases (fill the column height/width without distorting image)

Current situation is that image stays the same even after increasing column_height

column_height: 50
![image](https://user-images.githubusercontent.com/3348953/86521401-0399cf80-be59-11ea-91a4-96f3eaf72483.png)

column_height: 150
![image](https://user-images.githubusercontent.com/3348953/86521408-27f5ac00-be59-11ea-86f7-e930575ee72c.png)

tried clearing browser cache - didn't help
images file dimensions are much larger than button.

**Comment by kalkih** [comment]
Hesitant to do make this change, image is intended to be a replacement for the icon. Useful when there's no suitable mdi icon.
Scaling the image would break that use-case and make it pretty much useless in combination with a shortcut text.

Does the cover option fill your needs?

**Comment by theone11** [comment]
I tried the cover option before (and now again) the problem is that I need to scale(x,y) the images to fit th buttons otherwise they are cut. and this needs to be done also each time I change the buttons' layout.
![image](https://user-images.githubusercontent.com/3348953/90607248-a475fb80-e209-11ea-8a03-14a7f3daed86.png)

Can an option be added to allow scaling the images from the card defitions?

**Comment by g3n3r1c** [comment]
I made custom images for spotify playlists and am also struggling to scale them.
Perhaps an option to use fixed image sizes based on the number of shortcuts per row?

![playlist](https://user-images.githubusercontent.com/73752169/98756492-aed30c00-2398-11eb-9b4c-8ab1feecf648.jpg)

**Comment by mrask90** [comment]
How about the MDI icons? They do not seem to scale with column_height either.

![image](https://user-images.githubusercontent.com/61989041/116457012-30ddc100-a863-11eb-9233-569ec621e9a5.png)

**Comment by MickMorley** [comment]
I had the same issue and found this thread.

But just tried cover and it is working as expected.  Is @theone11 still having this issue?

All of my images are square in size and I must of gotten luck setting the column height to 100.

Here's my config

```
  - type: custom:mini-media-player
    entity: media_player.owntone_server
    hide:
      icon: true
    shortcuts:
      columns: 4
      column_height: 100
      buttons:
        - cover: /local/mod/klovechristmas.png
          type: playlist
          id: library:playlist:15
```

![image](https://user-images.githubusercontent.com/19698105/207449156-a7d750d2-48ad-454c-8c2f-950d8554a90a.png)
