### ISSUE TITLE
How to use the group option?

### ISSUE THREAD

**Issue by wormiedk** [kalkih/mini-media-player#360]
I am trying to set up my speakers to show as the example with the group option. However I am how to embed the group options inside another card? Which card type should I use.

If I enter:
```
title: Speakers
- type: entities
  entities:
    - type: custom:mini-media-player
      entity: media_player.multiroom_player
      group: true
      source: icon
      info: short
      hide:
        volume: true
        power: true
    - type: custom:mini-media-player
      entity: media_player.alrum
      group: true
      hide:
        controls: true
    - type: custom:mini-media-player
      entity: media_player.repos
      group: true
      hide:
        controls: true
```
Inside a custom card I get an error stating "No card type found". 
![image](https://user-images.githubusercontent.com/4417857/88627943-6e7fa480-d0ad-11ea-8527-c303321a8bb6.png)

The below config works (except idle) but doesn't give me volume for the other speakers in the group:
```
type: 'custom:mini-media-player'
entity: media_player.alrum
artwork: cover
idle:
  - when_paused: true
  - when_idle: true
speaker_group:
  platform: sonos
  show_group_count: true
  entities:
    - entity_id: media_player.alrum
      name: Alrum
      group: true
      hide:
        controls: true
    - entity_id: media_player.badevaerelse
      name: Bad
      group: true
      hide:
        controls: true
    - entity_id: media_player.repos
      name: Repos
      group: true
      hide:
        controls: true
```

It might be useful for beginners like me :) if more full configs where shared in the readme page...

**Comment by kalkih** [comment]
Hello, the entities card should work great, other potential cards are the vertical-stack-in-card and the stack-in-card remove the dash in front of type.
```
- type: entities
``` 
And move the indentation of everything else back one step.

```yaml
title: Speakers
type: entities
entities:
  - type: custom:mini-media-player
    entity: media_player.multiroom_player
    group: true
    source: icon
    info: short
    hide:
      volume: true
      power: true
  - type: custom:mini-media-player
    entity: media_player.alrum
    group: true
    hide:
      controls: true
  - type: custom:mini-media-player
    entity: media_player.repos
    group: true
    hide:
      controls: true
```
