### ISSUE TITLE
Add support for media players that do not support playing state

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-media-player#366]
Some media players do not have a playing state, in my case webOS TVs...

<img width="402" alt="image" src="https://user-images.githubusercontent.com/19761269/89124968-9ed5a180-d4f8-11ea-8149-89e7185ba643.png">

`mini-media-player` currently shows a play button

<img width="515" alt="image" src="https://user-images.githubusercontent.com/19761269/89124984-b2810800-d4f8-11ea-841e-cccd55dfb052.png">

Could you add a pause button beside the play button or a stop button `mdi-stop` to signify this?

**Comment by kalkih** [comment]
Hello,
You can achieve this with the following config:
```yaml
- type: custom:mini-media-player
  entity: media_player.example
  hide:
    play_stop: false
```
This will make the card display a stop button.
