### ISSUE TITLE
The card doesn't dispaly entity icon

### ISSUE THREAD

**Issue by bieniu** [kalkih/mini-media-player#369]
After update card to version 0.10.0 (2020.08.04) I don't have entities icons. I don't know why, but the icon is only displayed for Fire TV 4K stick.

![image](https://user-images.githubusercontent.com/478555/89264896-fdec0100-d633-11ea-998f-dd341304f1be.png)

My config:
```yaml
         - type: entities
            show_header_toggle: false
            state_color: true
            entities:
              - entity: binary_sensor.motion_salon
                secondary_info: last-changed
               - entity: fan.humidifier_salon
                secondary_info:
                  entity: sensor.humidifier_water_level
                  prefix: "poziom wody: "
                  postfix: " %"
              - fan.pedestal_salon
              - light.bulbs_salon
              - light.leds_salon
              - light.lamp_salon
              - input_select.light_scenes_salon
              - input_select.salon_harmony
              - type: custom:mini-media-player
                entity: media_player.bravia
                hide:
                  controls: true
                  volume: true
                  power: true
                  progress: true
                info: scroll
                group: true
              - type: custom:mini-media-player
                entity: media_player.denon
                hide:
                  controls: true
                  power: true
                  power_state: false
                  progress: true
                info: scroll
                group: true
              - type: conditional
                conditions:
                  - entity: media_player.dune
                    state_not: "unavailable"
                row:
                  type: custom:mini-media-player
                  entity: media_player.dune
                  hide:
                    volume: true
                    controls: true
                    power: true
                    source: true
                  info: scroll
                  group: true
              - type: custom:mini-media-player
                entity: media_player.firetv
                hide:
                  volume: true
                  controls: true
                  power: true
                  source: true
                info: scroll
                group: true
              - type: custom:mini-media-player
                entity: media_player.playstation
                hide:
                  controls: true
                  volume: true
                  power: true
                  progress: true
                  source: true
                info: scroll
                group: true
              - type: custom:mini-media-player
                entity: media_player.echo_show
                hide:
                  controls: true
                  volume: true
                  power: true
                  progress: true
                info: scroll
                group: true
                shortcuts:
                  label: "Skróty"
                  list:
                    - name: "RMF FM"
                      type: "service"
                      id: media_player.play_media
                      data:
                        entity_id: media_player.echo_show
                        media_content_type: "TUNEIN"
                        media_content_id: "RMF FM in everywhere group"
                    - name: "MUZO FM"
                      type: "service"
                      id: media_player.play_media
                      data:
                        entity_id: media_player.echo_show
                        media_content_type: "TUNEIN"
                        media_content_id: "MUZO FM in everywhere group"
                    - name: "Radio ZET"
                      type: "service"
                      id: media_player.play_media
                      data:
                        entity_id: media_player.echo_show
                        media_content_type: "TUNEIN"
                        media_content_id: "Radio ZET in everywhere group"
```
