### ISSUE TITLE
Problem with first show when i have add mini media player

### ISSUE THREAD

**Issue by pepeEL** [kalkih/mini-media-player#39]
Hi
I have added to my config as i show mini media player. After first login to HA i have an error but when go to other cards/tab and then come back to my first card with mini media player all is ok.
Why ?

`resources:
  - url: /local/mini-media-player.js?v=0.9.5
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.0.8
    type: js
  - url: /local/layout-card.js?ver=7db164
    type: js
  - url: /local/dark-sky-weather-card.js?ver=0.1.5
    type: js
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/slider-entity-row.js
    type: js

title: Mój dom
views:
##### POKOJE #####
  - id: pokoje
    icon: mdi:home-assistant
    title: Pomieszczenia
    panel: false
    badges:
      - sun.sun
      - updater.updater
    cards:
      - id: pokoje_salon
        type: custom:vertical-stack-in-card
        show_header_toggle: false
        title: Salon
        cards:
          - type: glance
            show_name: false
            entities:
              - sensor.salon_temperature
          - type: entities
            entities:
              - entity: light.salon_stol
                name: Oświetlenie nad stołem
                icon: mdi:lightbulb
              - entity: light.salon_kinkiety
                name: Oświetlenie kinkiety
                icon: mdi:lightbulb
              - entity: switch.fibaro_system_fgwpef_wall_plug_switch
                name: Salon gniazdo TV
                icon: mdi:power-socket-eu
              - entity: light.fibaro_system_fgrgbwm441_rgbw_controller_level_3
                name: LEDy 3
                icon: mdi:led-strip
              - entity: light.fibaro_system_fgrgbwm441_rgbw_controller_level_4
                name: LEDy 4
                icon: mdi:led-strip
              - entity: light.fibaro_system_fgrgbwm441_rgbw_controller_level_5
                name: LEDy 5
                icon: mdi:led-strip
              - entity: light.fibaro_system_fgrgbwm441_rgbw_controller_level_6
                name: LEDy 6
                icon: mdi:led-strip
              - entity: light.fibaro_system_fgrgbwm441_rgbw_controller_level_7
                name: LEDy 7
                icon: mdi:led-strip
              - type: divider
          - type: custom:mini-media-player
            entity: media_player.tv_salon
            icon: mdi:television
            hide_controls: false
            volume_stateless: true
            hide_volume: false
            power_color: true
            show_source: true
          - type: custom:mini-media-player
            entity: media_player.denon_salon
            icon: mdi:audio-video
            hide_controls: false
            hide_volume: false
            power_color: true
            scroll_info: true
            show_source: true
`

![1](https://user-images.githubusercontent.com/16692223/49608794-e1e51780-f999-11e8-8d9b-9e756e295707.jpg)

![2](https://user-images.githubusercontent.com/16692223/49608797-e4e00800-f999-11e8-927f-68670c952aad.jpg)

**Comment by kalkih** [comment]
Hello,
This is an issue when using the card nested inside the `custom:vertical-stack-in-card` card.
Custom cards doesn't always play nice together and I can't maintain support for every custom card available unfortunately.

There are a couple of issues opened in the vertical-stack-in-card repo regarding this already ([#23](https://github.com/custom-cards/vertical-stack-in-card/issues/23), [#22](https://github.com/custom-cards/vertical-stack-in-card/issues/22))

Try updating vertical-stack-in-card to the [latest](https://github.com/custom-cards/vertical-stack-in-card/releases/latest) version if you haven't already, [#28](https://github.com/custom-cards/vertical-stack-in-card/pull/28) might have fixed this issue.

Btw, I recommend you to switch over to the bundle version of mini-media-player (follow the install instructions again).

**Comment by pepeEL** [comment]
I have latest 0.0.8 version vertical-stack-card

What you mean write about 

> Btw, I recommend you to switch over to the bundle version of mini-media-player (follow the install instructions again).

**Comment by pepeEL** [comment]
i folowed step by step by manual and the same probem is...

**Comment by kalkih** [comment]
Ok, then `vertical-stack-in-card` doesn't work properly when this card is nested.
If you use this card outside of the vertical-stack-in-card it will work as expected.

You can also try replacing the vertical-stack-in-card with a [vertical-style-card](https://github.com/matisaul/vertical-style-card).

**Comment by pepeEL** [comment]
In vertical-style-card is also problem. But on this also after refresh not show entity mini-media-player

![3](https://user-images.githubusercontent.com/16692223/49631749-75970200-f9f3-11e8-9b4f-8678d19b424e.jpg)

**Comment by kalkih** [comment]
Hey @pepeEL 
I just tried this myself and both vertical-stack-in-card and vertical-style-card work perfectly fine together with the mini-media-player.

Make sure you've followed the installation instructions correctly and are using the latest version of each card and Home Assistant.

<img width="516" alt="screenshot 2018-12-07 at 17 49 40" src="https://user-images.githubusercontent.com/457678/49661160-a190a280-fa48-11e8-8ae4-222e017c2372.png">


Example card configuration:
```
- type: custom:vertical-stack-in-card
  title: custom:vertical-stack-in-card
  cards:
    - entity: media_player.chromecast_badrum
      type: custom:mini-media-player
    - entity: media_player.chromecast_sovrum
      type: custom:mini-media-player
    - entity: media_player.chromecast_vardagsrum
      type: custom:mini-media-player

- type: custom:vertical-style-card
  title: custom:vertical-style-card
  cards:
    - entity: media_player.chromecast_badrum
      type: custom:mini-media-player
    - entity: media_player.chromecast_sovrum
      type: custom:mini-media-player
    - entity: media_player.chromecast_vardagsrum
      type: custom:mini-media-player
```
