### ISSUE TITLE
`id` as an attribute identifier only

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-media-player#399]
I'm trying to set the state of a shortcut button on Spotify which plays playlists.

Spotify exposes the current playing playlist as `media_playlist` as the name of the playlist, not the ID, so currently there is no way for the state of the 

What I'm proposing is to designate `id` as the state of the shortcut, where it must match the attribute, but should not be used for playlist. Currently, when `attribute:` cannot be used alongside `type: service`.

If a shortcut button calls a service, instead of...

```yaml
shortcuts:
  buttons:
    - icon: 'mdi:sunglasses'
      id: media_player.play_media
      type: service
      data:
        entity_id: media_player.spotify
        media_content_id: 'spotify:playlist:xxxxx'
        media_content_type: playlist
```

My proposal:

```yaml
shortcuts:
  attribute: media_playlist
  buttons:
    - icon: 'mdi:sunglasses'
      id: Dr Disrespect
      type: service
      service_name: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_id: 'spotify:playlist:xxxxx'
        media_content_type: playlist
```

`*_name` for other types such as `playlist` or `script`.
