### ISSUE TITLE
Spotify playing playlist doesn't work

### ISSUE THREAD

**Issue by zygote279** [kalkih/mini-media-player#425]
Fairly sure this is me, rather than this very nifty card, but have picked through fairly carefully and can't spot my error.

Just trying to play a simple playlist with a button:
- Have spotify integration installed and running
- Have followed the instructions in github (code below)
- Have tested the device connection by using the text to speech option and all plays perfectly, so feels like it's something with the spotify connection or the below code being wrong??

Can anyone help with any ways I can test/diagnose this?

```
entity: media_player.all_master_bedroom
type: 'custom:mini-media-player'
artwork: cover
source: icon
hide:
  volume: true
shortcuts:
  columns: 3
  buttons:
    - icon: 'mdi:cat'
      type: playlist
      id: 'spotify:user:spotify:playlist:37i9dQZF1E36RtrVYerk3U'

```
