### ISSUE TITLE
spotify playlist not working

### ISSUE THREAD

**Issue by jaburges** [kalkih/mini-media-player#447]
Hi there,
I'm able to drop the playlist id in a browser on my PC, and it opens in Spotify app with the right playlist.
However it is not working from HA in Lovelace.

```yaml
- type: 'custom:mini-media-player'
                entity: media_player.living_room
                artwork: cover 
                speaker_group:
                  platform: sonos
                  show_group_count: true
                  entities:
                    - entity_id: media_player.living_room
                      name: Living room
                    - entity_id: media_player.bedroom
                      name: Bedroom                               
                    - entity_id: media_player.nursery
                      name: Nursery
                shortcuts:
                  columns: 4
                  buttons:
                    # Start predefined playlist
                    - icon: mdi:cat
                      type: playlist
                      id: spotify:user:{USERNAME}:album:3FEYYF2DDb5uzQsYtWa34j
                    - icon: mdi:rodent
                      type: playlist                   
                      id: spotify:album:38BYpjGvtDXjUi5hgDyTz1
                    - icon: mdi:dog
                      type: playlist
                      id: spotify:album:52ZI4mxoOizsmloKZfvesC
                    - icon: mdi:rabbit
                      type: playlist
                      id: spotify:album:40tVLyPjoMbpKWEPdZ63Gg                                
                    - icon: mdi:snowflake
                      type: playlist
                      id: spotify:user:{USERNAME}:playlist:7orAWQDfHhNJzoRHfVJjBi
                    - icon: mdi:pine-tree
                      type: playlist
                      id: spotify:user:{USERNAME}:playlist:37i9dQZF1DX6R7QUWePReA
                    - icon: mdi:saxophone
                      type: playlist
                      id: spotify:playlist:7orAWQDfHhNJzoRHfVJjBi
```

All the above playlists (mostly for my son :) ) work from a browser URI, so not entirely sure what I need to ensure they load in the card?

**Comment by plumped** [comment]
This has nothin to do with the mediplayer. Sonos is not supporting direct playing. It is possible to use the spotify service in the sonos app, but not with HA.

You have to use scripts as type instead of playlist than it works.
Use the integration beta (Sonos Beta) from HACS (Integrations)

Afterwards create your scripts as follows:

service: media_player.play_media
  data:
    entity_id: media_player.sonos_stue_1
    media_content_id: 'https://open.spotify.com/album/1bt6q2SruMsBtcerNVtpZB'
    media_content_type: music

**Comment by jaburges** [comment]
Ah - damn it Sonos! weird I cant find their github now with their API as i raised an issue about direct play what feels like last year.

Any idea if this is usable (seems local so maybe useful I'm not sure) https://github.com/jishi/node-sonos-http-api

in the meantime will try your solution - thank you again!

**Comment by jaburges** [comment]
confirmed this works - although for anyone who doesnt want to create a script for each playlist, for each sonos I used the extra data to send the entity:

lovelace card:
```yaml
- type: 'custom:mini-media-player'
                entity: media_player.nursery
                artwork: cover 
                scale: 0.5
                speaker_group:
                  platform: sonos
                  entities:
                    - entity_id: media_player.living_room
                      name: Living room
                    - entity_id: media_player.bedroom
                      name: Bedroom                               
                shortcuts:
                  columns: 4 
                  buttons:
                    # Start predefined playlist
                    - icon: mdi:cat
                      type: script
                      id: script.cbp_more_please
                      data:
                        sonos_entity: media_player.nursery
                    - icon: mdi:rodent
                      type: script                   
                      id: script.cbp_sleep_tight
                      data:
                        sonos_entity: media_player.nursery 
```

script:
```yaml
sunday_jazz:
  sequence:
    - service: media_player.play_media
      data:
        entity_id: "{{ sonos_entity }}"
        media_content_id: 'https://open.spotify.com/playlist/37i9dQZF1E4DJL8gEKmI0t'
        media_content_type: music    
```
