### ISSUE TITLE
No artwork on universal media player

### ISSUE THREAD

**Issue by blackjid** [kalkih/mini-media-player#45]
For some reason I cannot make the card to show the artwork.

I have two media players, one from a chromecast audio and other is a universal media player that has the former as the first of its childrens. The universal media player inherits almost all attributes from the chomrecast audio.

The chromecast audio shows the artwork fine, but the universal media player don’t.

If I check the state of both media players, both have their entity_picture attribute with the same value.

I don’t see any errors in the js console nor it in the mail ha logs.

My config looks like this

```
- type: custom:mini-media-player
entity: media_player.living_music
name: Living Music
artwork: cover
power_color: true
show_progress: true
```

Any idea what could be the problem?

**Comment by blackjid** [comment]
I found out that the problem is in this lines

https://github.com/kalkih/mini-media-player/blob/fd8db13322c39e1a8e670a99937180c9d90e8b6a/mini-media-player.js#L225-L231

On the universal media player, `this.thumnail` is `false` so the `computeArtwork` function returns false.

From the testing I did, I'd say that the if statement on line 225 is evaluated true, so the `this._fetchThumbnail();` it's, in fact, being called.

I hope that helps, I'll try to continue looking into it.

**Comment by kalkih** [comment]
Hey,
Sounds like something going wrong when fetching the thumbnail from the backend, and it ends up in the catch statement.
https://github.com/kalkih/mini-media-player/blob/fd8db13322c39e1a8e670a99937180c9d90e8b6a/mini-media-player.js#L736-L746

What does your universal media player configuration look like?
And what type of media players does it include?

Thanks!

**Comment by kalkih** [comment]
Hey @blackjid 
I'm unable to reproduce this.
What does your universal media player configuration look like?
And what type of media players does it include?

**Comment by blackjid** [comment]
This is my universal media player

They include two media players
- `media_player.living_room_audio` which is a Chromecast Audio
- `media_player.marantz` which is a Marantz recevier

```
media_player:
  - platform: denonavr
    host: !secret marantz_host
    name: marantz
    scan_interval: 2
    supress_warning: true

  - platform: universal
    name: Living Music
    children:
      - media_player.living_room_audio
      - media_player.marantz
    state_template: >
      {% if is_state('media_player.marantz', 'on') %}
        {{ states('media_player.living_room_audio') }}
      {% else %}
        off
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.marantz
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.marantz
      volume_up:
        service: media_player.volume_up
        data_template:
          entity_id: media_player.marantz
      volume_down:
        service: media_player.volume_down
        data_template:
          entity_id: media_player.marantz
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.marantz
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.marantz
          source: '{{ source }}'
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.marantz
          volume_level: '{{ volume_level }}'
    attributes:
      volume_level: media_player.marantz|volume_level
      source: media_player.marantz|source
      source_list: media_player.marantz|source_list
      is_volume_muted: media_player.marantz|is_volume_muted
```
