### ISSUE TITLE
icon problems?

### ISSUE THREAD

**Issue by vMeph** [kalkih/mini-media-player#46]
not sure if im doing something wrong but it seems its ignoring the use of icon grr
```
entities:
  - entity: media_player.echo_dot
    group: true
    hide_controls: true
    hide_media_info: true
    hide_power: true
    hide_volume: true
    icon: 'mdi:router-wireless'  <---------- is ignoring
    name: Alexa Echo Dot
    show_tts: alexa
    type: 'custom:mini-media-player'
```

![1](https://user-images.githubusercontent.com/12812111/50387558-10335880-06f7-11e9-8311-41dac8edbb1d.jpg)
