### ISSUE TITLE
Idle_view code block resetting when editing via UI

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-media-player#468]
With v0.12.0, idle_view code keeps getting reset to `idle_view: '[object Object]'` when editing from UI.

**Comment by OverZealous** [comment]
To add to this, I have `idle_view` set to this:

```yaml
idle_view:
  when_idle: true
  when_standby: true
```

Looks like the `idle_view` property in the UI editor is expecting a simple string, rather than nested options. This wouldn't be an issue, except the Lovelace editor defaults to the UI editor even with this "incorrect" value.
