### ISSUE TITLE
Shuffle button not displaying status when artwork: is set to material

### ISSUE THREAD

**Issue by scstraus** [kalkih/mini-media-player#477]
Hi, I use mini-media-player in a couple places in my lovelace config. In one place I use ```artwork:material```, and in the other I use ```artwork:full-cover```. Only the one with ```artwork:full-cover``` correctly shows the state of shuffle as a different color when shuffle is activated. See below of screenshots of both media players with shuffle active and their configs below that.

![image](https://user-images.githubusercontent.com/7644023/105035237-f346ec00-5a5a-11eb-81b2-2d348a33ac2b.png)

```
  - entity: media_player.forked_daapd_server

    type: custom:mini-media-player
    name: Music
    source: icon
    artwork: material
    group: true
    hide:
      shuffle: false
      icon: true
      power: true
    shortcuts:
      columns: 4
      buttons:
        - name: "MIX"
          type: source
          id: "A: 4+5 Star (playlist)"
        - name: "JAZZ"
          type: source
          id: "Good Jazz (playlist)"
        - name: "ROCK"
          type: source
          id: "Good Rock (playlist)"
        - name: "POP"
          type: source
          id: "Good Pop (playlist)"
        - name: "CLASSIC"
          type: source
          id: "Classical (playlist)"
        - name: "BLACK"
          type: source
          id: "Good Black (playlist)"
        - name: "ELECTRO"
          type: source
          id: "Good Electronica (playlist)"
        - name: "KIDS"
          type: source
          id: "Kids - English (playlist)"
        - name: "KULTURA"
          type: source
          id: "radio kultura (playlist)"
        - name: "CLASSIC"
          type: source
          id: "Classical Radio (playlist)"
        - name: "JAZZ24"
          type: source
          id: "Jazz24 Radio (playlist)"
        - name: "EUROPA2"
          type: source
          id: "radio2 (playlist)"
```

![image](https://user-images.githubusercontent.com/7644023/105035268-00fc7180-5a5b-11eb-8af1-743be4a247e6.png)

```
  - entity: media_player.forked_daapd_server
    type: custom:mini-media-player
    name: Music
    source: icon
    artwork: full-cover
    group: true
    hide:
      shuffle: false
      icon: true
      power: true
    shortcuts:
      columns: 4
      buttons:
        - name: "MIX"
          type: source
          id: "A: 4+5 Star (playlist)"
        - name: "JAZZ"
          type: source
          id: "Good Jazz (playlist)"
        - name: "ROCK"
          type: source
          id: "Good Rock (playlist)"
        - name: "POP"
          type: source
          id: "Good Pop (playlist)"
        - name: "CLASSIC"
          type: source
          id: "Classical (playlist)"
        - name: "BLACK"
          type: source
          id: "Good Black (playlist)"
        - name: "ELECTRO"
          type: source
          id: "Good Electronica (playlist)"
        - name: "KIDS"
          type: source
          id: "Kids - English (playlist)"
        - name: "KULTURA"
          type: source
          id: "radio kultura (playlist)"
        - name: "CLASSIC"
          type: source
          id: "Classical Radio (playlist)"
        - name: "JAZZ24"
          type: source
          id: "Jazz24 Radio (playlist)"
        - name: "EUROPA2"
          type: source
          id: "radio2 (playlist)"
```
