### ISSUE TITLE
Code Editor-only options transform into `[object Object]` when using Lovelace Visual editor

### ISSUE THREAD

**Issue by TheGroundZero** [kalkih/mini-media-player#478]
Some of the options for the `custom:mini-media-player` cannot be set via the Visual Editor of Lovelace.  
To set these up, you need to click the `Show Code Editor` link and edit the yaml. Or you need to modify `ui-lovelace.yaml`.

However, if these settings are set using YAML (and saved) and the card is later re-opened in the Visual Editor, the relevant code pieces as replaced by `[object Object]` and the settings are undone.

For example, notice how the `idle_view` configuration has been replaced.

![image](https://user-images.githubusercontent.com/2406013/105338218-3330df00-5bd3-11eb-8a90-f163e63a0cb8.png)

```yaml
type: 'custom:mini-media-player'
idle_view: '[object Object]'
[... deleted irrelevant lines ...]
```

This change only occurs once the card is loaded in the Visual Editor.
If you open the Code Editor for the full dashboard (or top-layer card when using nested cards), you can still see the original code.

```yaml
type: vertical-stack
cards:
  - type: 'custom:mini-media-player'
    [... deleted irrelevant lines ...]
    idle_view:
      when_idle: true
```

These configurations should either be stored somehow, or Visual Editor shouldn't be an option if any of these config settings are used.
