### ISSUE TITLE
playlist shortcut type does not support user specific playlist like Mix Tapes or Discovery Weekly

### ISSUE THREAD

**Issue by Clusters** [kalkih/mini-media-player#497]
Isn't it possible to replay user specific playlists like the mix tapes or the discovery weekly playlist? The weekly playlist is even selectable via the spotify media player. The mix tapes are missing there too though.

I was not able to find any existing issues to address this, so I wonder if I'm doing something wrong here.

```
  - icon: 'mdi:beach'
    type: playlist
    id: 'spotify:user:MYUSERID:playlist:4MGMq5a7k7XLTvo0PkYEH1' # custom playlist -> working
  - icon: 'mdi:feature-search'
    type: playlist
    id: 'spotify:user:MYUSERID:playlist:37i9dQZEVXcTvyRUPhGD5D' # discovery weekly playlist -> not working
```

If this is a known limitation. Do you have any script or automation examples on how to copy the discovery weekly playlist to a custom one? If I recall correctly, this was possible within IFTTT?

**Comment by kongo09** [comment]
You should be able to start the Discover Weekly playlist by calling a service like this:
```
service: media_player.play_media
data:
  media_content_id: '{{ playlist_id }}'
  media_content_type: playlist
entity_id: media_player.spotify
```
Replace `{{ playlist_id }}` with your personal link to your Discover Weekly playlist, something like
```
https://open.spotify.com/playlist/37i9dQZEVXcTvyRUPhGD5D
```

**Comment by kalkih** [comment]
@kongo09 Thanks for sharing.

If that works, you should also be able to specify it directly in a shortcut since that relies on `media_player.play_media` in the background.

e.g.
```yaml
  - icon: 'mdi:feature-search'
    type: playlist
    id: 'https://open.spotify.com/playlist/37i9dQZEVXcTvyRUPhGD5D'
```
