### ISSUE TITLE
Icon not shown anymore

### ISSUE THREAD

**Issue by chemelli74** [kalkih/mini-media-player#508]
Since updating to latest version, icon is not shown anymore.

My lovelace code:

```
type: vertical-stack
cards:
  - type: 'custom:mini-media-player'
    entity: media_player.echo_dot_salotto
    icon: 'mdi:amazon-alexa'
    artwork: cover
    hide:
      source: true
      power: true
  - type: entities
    entities:
      - entity: switch.echo_dot_salotto_do_not_disturb_switch
```

**Comment by kongo09** [comment]
I can confirm this. If there is no icon configured for the entity and Home Assistant assumes one (shown in light grey in the entity configuration), ´mini-media-player´ does not show any icon itself. Not the assumed one by HA and also no configured one.

![image](https://user-images.githubusercontent.com/640121/115127780-8dc2b700-9fd9-11eb-8a53-14dce07464d6.png)

with card configuration:
```
type: 'custom:mini-media-player'
entity: media_player.wohnzimmer
icon: 'mdi:amazon-alexa'
artwork: cover
hide:
  source: true
  power: true
```

If you set an icon in the entity configuration, ´mini-media-player´ shows that icon, regardless of what you configure in the actual card:

![image](https://user-images.githubusercontent.com/640121/115127789-a632d180-9fd9-11eb-91fe-d85e295e8a41.png)

with card configuration:
```
type: 'custom:mini-media-player'
entity: media_player.wohnzimmer
artwork: cover
hide:
  source: true
  power: true
```
