### ISSUE TITLE
Yamaha MusicCast

### ISSUE THREAD

**Issue by ipodmusicman** [kalkih/mini-media-player#528]
Hi there

I used the mini-media-player card with a custom MusicCast Yamaha integration via HACS in order to allow me to group MusicCast devices.  Now with HA 2021.07, the grouping feature was brought into the official integration.  I removed the HACS integration and configured the updated Yamaha MusicCast integration.

I configured the mini-media-player card with the new entities.  Since there was no longer a musiccast_yamaha platform, I changed this to media_player as there was no other platform bearing the name yamaha or musicast.

When I clicked on the card to group all devices, I got the following error:

Failed to call service media_player/join. extra keys not allowed @ data['master']

Please advise if this is a bug or if there is anything I need to do?

**Comment by ppanagiotis** [comment]
Same here!

**Comment by ppanagiotis** [comment]
@ipodmusicman have a look here. It looks like at the next release this is fixed. 
(I already build it through dev branch and it looks working as expected.)

**Comment by orestesgaolin** [comment]
I have the same problem, can't wait for the release :)

**Comment by ipodmusicman** [comment]
@ppanagiotis can you please advise how to build this as I cannot wait for a new release to come out - whenever that will be.

**Comment by ppanagiotis** [comment]
> @ppanagiotis can you please advise how to build this as I cannot wait for a new release to come out - whenever that will be.

Sure. Delete everything under www/community/mini-media-player/ and the put this file and restart home assistant. https://ufile.io/vrs39upp

**Comment by ipodmusicman** [comment]
Great, thanks very much.  Works like a charm!

**Comment by KaSroka** [comment]
When can we expect the release?

**Comment by niqu1982** [comment]
> 
> 
> Hi there
> 
> I used the mini-media-player card with a custom MusicCast Yamaha integration via HACS in order to allow me to group MusicCast devices. Now with HA 2021.07, the grouping feature was brought into the official integration. I removed the HACS integration and configured the updated Yamaha MusicCast integration.
> 
> I configured the mini-media-player card with the new entities. Since there was no longer a musiccast_yamaha platform, I changed this to media_player as there was no other platform bearing the name yamaha or musicast.
> 
> When I clicked on the card to group all devices, I got the following error:
> 
> Failed to call service media_player/join. extra keys not allowed @ data['master']
> 
> Please advise if this is a bug or if there is anything I need to do?

Can You show Your configuration from lovelace card ?

**Comment by michelotten** [comment]
I updated to the latest version, but still getting this error message with below config. Could you look into this?

```
      - type: custom:mini-media-player
        entity: media_player.nest_audio_kast
        speaker_group:
          platform: media_player
          show_group_count: true
          entities:
            - entity_id: media_player.nest_audio_kast
              name: Kast
            - entity_id: media_player.nest_audio_keuken
              name: Keuken
```

Thanks!
