### ISSUE TITLE
Missing media_list examples

### ISSUE THREAD

**Issue by mlevit** [kalkih/mini-media-player#53]
We're missing examples of how to implement the `media_list` feature. I've been trying to get it to work with Google Music but can't seem to figure it out.

**Comment by kalkih** [comment]
Hey,
The `media_list` syntax is the same as `media_buttons`. They both take [media objects](https://github.com/kalkih/mini-media-player#media-object-options).

So if you follow the [Player with media_buttons example](https://github.com/kalkih/mini-media-player#player-with-media-buttons), you just have to change `media_buttons` to `media_list`

```yaml
- type: custom:mini-media-player
  entity: media_player.spotify
  name: Spotify Player
  artwork: cover
  show_source: full
  media_list:
    - name: Lowkeee
      type: playlist
      url: spotify:user:kalkih:playlist:1HsopVo0BO6p5Qg52ly5oq
    - name: RapCaviar
      type: playlist
      url: spotify:user:spotify:playlist:37i9dQZF1DX0XUsuxWHRQd
    ...
```

This option is getting changed with the next update, I'll also try to make the instructions clearer.
Thanks!
