### ISSUE TITLE
"Idle_view" after X minutes doesn't work

### ISSUE THREAD

**Issue by mat4444** [kalkih/mini-media-player#531]
Hi there,
The following config option does not seem to work on my Sonos One player : `idle_view` `when_paused` `after` x minutes. I have read the documentation that says the `after` option only works on platform with the `media_position_updated_at `attribute, which is the case for the Sonos One.

In my case, the media player immediately renders as idle when it's paused, instead of waiting 2 minutes. Here is my config for review.

```
- type: custom:mini-media-player
  entity: media_player.sonos_salon    
   artwork: material
   show_source: true
   show_progress: true
   idle_view:
       when_idle: true
       when_standby: true
       when_paused: true
       after: 2
```
