### ISSUE TITLE
Color change of buttons

### ISSUE THREAD

**Issue by criticallimit** [kalkih/mini-media-player#541]
I'm using several buttons for my radio stations. 
Is there any way to change color of the button when selected, to see which radiostation is active playing?

**Comment by kalkih** [comment]
Hello,

When playing a radiostation does the media player entity contain an attribute that matches the radiostation URL from the shortcut? If so you should be able to use the `attribute` setting in the [shortcut object](https://github.com/kalkih/mini-media-player#shortcuts-object).

**Comment by criticallimit** [comment]
thanx for your quick reply.
I´m very new to all this. Do you have an example for using attribute settings in the shortcut objects?

Here is my card:

type: custom:mini-media-player
entity: media_player.browser_mod_dd4fc6b1_2ff19a76
volume_stateless: false
icon_state: true
hide:
  volume: false
  power: true
shortcuts:
  columns: 1
  buttons:
    - name: Eins Live
      type: music
      id: https://1liveuni-lh.akamaihd.net/i/1LIVE_HDS@179577/master.m3u8
    - name: SWR 3
      type: music
      id:https://swr-edge-10b9-fra-dtag-cdn.cast.addradio.de/swr/swr3/live/aac/96/stream.aac?lwPTg4
      type: music
      id: https://wdr2-lh.akamaihd.net/i/wdr2_ruhrgebiet@384692/master.m3u8
    - name: radioKW
      type: music
      id: http://radiokw.cast.addradio.de/radiokw/simulcast/high/stream.mp3
    - name: Antenne Bayern
      type: music
      id: https://www.antenne.de/webradio/antenne.m3u
    - name: Radio Hamburg
      type: music
      id: https://frontend.streamonkey.net/rhh-1036?aggregator=linkradiohamburgde
    - name: nrj Hitradio
      type: music
      id: http://cdn.nrjaudio.fm/adwz1/de/33001/aac_64.mp3
    - name: nrj HITS
      type: music
      id: http://cdn.nrjaudio.fm/adwz1/de/33019/aac_64.mp3
name: Web Radio auf iPad
icon: mdi:radio
artwork: material
source: full
info: short
sound_mode: full

**Comment by kalkih** [comment]
You'd have to check the entity `media_player.browser_mod_dd4fc6b1_2ff19a76` for its attribute to see if there's one that exposed thr url to the radiostation while active.

```yaml
type: custom:mini-media-player
entity: media_player.browser_mod_dd4fc6b1_2ff19a76
volume_stateless: false
icon_state: true
hide:
volume: false
power: true
shortcuts:
  attribute: "name_of_the_attribute" # The name of the attribute (if there is one that matched the radiostation url while active)
  columns: 1
  buttons:
  - name: Eins Live
    type: music
    id: https://1liveuni-lh.akamaihd.net/i/1LIVE_HDS@179577/master.m3u8
```
