### ISSUE TITLE
Media player state shown as on when state attribute is unavailable

### ISSUE THREAD

**Issue by parautenbach** [kalkih/mini-media-player#552]
I have a media player that looks like it's on when the state of the smart plug which is unavailable. I think it should rather show as off in that case. 

Here is what it looks like:
<img width="507" alt="Screenshot 2021-10-12 at 21 51 06" src="https://user-images.githubusercontent.com/743320/137020120-9d25c0a5-1220-46a2-81c7-2838f7a5e518.png">

My universal media player using the smart plug is set up like this:
```
media_player:
  - platform: universal
    name: Main Bedroom Universal
    children:
      - media_player.main_bedroom
    commands:
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.smart_plug_1
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.smart_plug_1
    attributes:
      state: switch.smart_plug_1
```

And here is my card config:
```
    cards:
      - type: custom:mini-media-player
        name: Main Bedroom
        entity: media_player.main_bedroom_universal
        artwork: cover
        volume_stateless: true
        toggle_power: false  # make it use turn_on/turn_off
        hide:
          power: false
          power_state: false
          volume: false
          mute: true
        idle_view:
          when_idle: false
          when_paused: false
          when_standby: false
        background: '/local/tivoli-model-three.png'
```
