### ISSUE TITLE
Color each button individually.

### ISSUE THREAD

**Issue by tamet83** [kalkih/mini-media-player#615]
Hello,

I'm trying to solve this little problem. I have a card for my sonos Beam and I'd like to use the extra function for speech enhancement and night sound.

This is my card aspect:
<img width="449" alt="Schermata 2022-03-01 alle 12 48 50" src="https://user-images.githubusercontent.com/7949570/156173096-d78e5774-f85f-4581-9c43-6c6e417a62d8.png">

And the related code:

```yaml
 - type: vertical-stack
    cards:
      - type: custom:mini-media-player
        entity: media_player.salotto
        artwork: cover
        name: Salotto
        icon: mdi:soundbar
        icon_state: true
        volume_stateless: false
        volume_step: 5
        sound_mode: full
        hide:
          power_state: false
          controls: false
        shortcuts:
          columns: 2
          buttons:
            - name: Dialoghi
              icon: mdi:account-voice
              type: service
              id: switch.toggle
              data:
                entity_id: switch.sonos_salotto_speech_enhancement
            - name: Notte
              icon: mdi:weather-night
              type: service
              id: switch.toggle
              data:
                entity_id: switch.sonos_salotto_night_sound
```

I tried to use the `--mini-media-player-button-color` but I noticed it works on all buttons.
I also tried to use this part of code:

```yaml
            card_mod:
                style: |
                  :host {
                    --mini-media-player-button-color: #2879ae
                      {% if is_state('switch.sonos_salotto_speech_enhancement', 'on') %} #2879ae 
                      {% else %} grey {% endif %};
                    }
```
Does anyone have some advice to get that button colored?

Many thanks
