### ISSUE TITLE
Echo devices: Speaker groups not supported?

### ISSUE THREAD

**Issue by pedolsky** [kalkih/mini-media-player#629]
Hello kalkih, thank you very much for your awesome work!

Could it be that Echo speaker groups (platform: media_player) are not supported? Grouping is not possible, the buttons don’t react.

Here is my example config, maybe it’s misconfigured:

```
type: custom:mini-media-player
hide:
  power: true
  icon: true
  source: true
speaker_group:
  platform: media_player
  show_group_count: true
  expanded: true
  supports_master: true # tried also with 'false'
  entities:
    - entity_id: media_player.echo_dot
      name: Echo Küche
    - entity_id: media_player.echo_show
      name: Echo Schlafen
entity: media_player.echo_show # tried also with 'media_player.echo_dot'
```
Thank you in advance!
