### ISSUE TITLE
Clicking on a dropdown while in the card editor preview, will unexpectedly close the editor

### ISSUE THREAD

**Issue by sdrapha** [kalkih/mini-media-player#632]
Steps to reproduce the bug:

create any card with a dropdown:

generic example:
```yaml
type: custom:mini-media-player
entity: media_player.nest_big2
shortcuts:
  label: 'Target speaker:'
  list:
    - name: Basement Screen
      type: source
      id: basement_screen
      icon: mdi:television
    - name: TV Chromecast
      type: source
      id: tv_chromecast
      icon: mdi:television
```

Test the card on the preview side, the second click on the dropdown will force close the whole editor.

![image](https://user-images.githubusercontent.com/25059996/157090727-645fc578-7797-42d4-9cc4-c5bb745996d4.png)
