### ISSUE TITLE
Unable to display image in shortcuts list

### ISSUE THREAD

**Issue by rrowe629** [kalkih/mini-media-player#637]
I'd like to be able to display a thumbnail image of an album cover in a shortcuts dropdown list. I know "cover" is only supported for buttons, but "image" doesn't seem to work for lists in shortcuts. Here's a snippet of the YAML I'm using:
```
shortcuts:
  label: Albums
  list:
    - name: Allman Brothers/Eat a Peach
      image: >-
        http://xx.xx.xx.xx:8123/local/thumbnails/11d5e515-2bed-4f68-8d60-44cfa2ef99a1.jpg
      type: service
      id: media_player.play_media
      data:
        entity_id: media_player.garage
        media_content_type: album
        media_content_id: A:ALBUM/Eat%20a%20Peach
```
I've tried various options for the image value such as:
```
      image: >-
        "http://xx.xx.xx.xx:8123/local/thumbnails/11d5e515-2bed-4f68-8d60-44cfa2ef99a1.jpg"

      image: >-
        /local/thumbnails/11d5e515-2bed-4f68-8d60-44cfa2ef99a1.jpg

      image: >-
        "/local/thumbnails/11d5e515-2bed-4f68-8d60-44cfa2ef99a1.jpg"
```
I can paste the image URL into a browser and the image displays. Tried with a .png image rather than .jpg, but got the same results. Just to be clear, the shortcut works, it just doesn't show an image in the dropdown. Using a Sonos system with v1.16.2 and tested with both Safari and Firefox.
