### ISSUE TITLE
Addition to add groups as an output

### ISSUE THREAD

**Issue by paddy0407** [kalkih/mini-media-player#64]
Is it possible to add non media_player.outputs for example group.all_media, specifically, to allow the TTS function to be broadcast to all speakers within a group at once, like throughout a full house.

**Comment by iantrich** [comment]
Google Home?

**Comment by paddy0407** [comment]
Possibly a mixture of Google and non-google devices. I was seeing if the grouping could be managed from within HA or the card as opposed to something like the Google home app.

**Comment by kalkih** [comment]
Hello,
This will be possible in the next release, thanks to the new TTS options added in #61 by @Devqon.
You'll be able to optionally specify which entity/entities to target with the TTS, including groups.

Examples
```yaml
# Will send TTS messages to all entities within the group "google_home".
- entity: media_player.avr
  type: custom:mini-media-player
  tts:
    platform: google
    entity_id: group.google_home
```
```yaml
# Will send TTS messages to all listed entities.
- entity: media_player.avr
  type: custom:mini-media-player
  tts:
    platform: google
    entity_id:
      - media_player.chromecast_kontor
      - media_player.chromecast_sovrum
      - media_player.chromecast_badrum
      - group.google_home
```
