### ISSUE TITLE
mini media player in state switch cards overlay each other

### ISSUE THREAD

**Issue by satyambaba** [kalkih/mini-media-player#641]
When we use mini media player in conjunction with custom state switch. Multiple states causes media player to overlay each other. Please refer to the below screenshot. I am on HA V2022.4.1 running on Home Assistant Blue, I am using Chrome browser (Version 100.0.4896.75 (Official Build) (64-bit)).

![Screenshot_20220303-033237](https://user-images.githubusercontent.com/6833101/156457347-d45c2087-6d9c-4945-8ad0-e804c9642691.jpg)

The yaml for that card is -

```yaml
type: custom:state-switch
entity: media_player.bedroom_display
states:
  playing:
    type: custom:mini-media-player
    volume_stateless: false
    artwork: full-cover
    entity: media_player.bedroom_display
    sound_mode: full
    source: full
    group: true
    info: scroll
  paused:
    type: custom:mini-media-player
    volume_stateless: false
    artwork: material
    entity: media_player.bedroom_display
    sound_mode: full
    source: full
    group: true
    info: scroll
```

The moment I remove one state value (either "playing" or "paused"), I don't see the overlay.
