### ISSUE TITLE
Failed to call service ga/join. Service not found.

### ISSUE THREAD

**Issue by spencerthayer** [kalkih/mini-media-player#648]
I am getting the following error, `Failed to call service ga/join. Service not found.`, when I am trying to add **media_player.google_in_bedroom** to group play.

```yaml
type: custom:mini-media-player
name: Bedroom Sleep Modes
entity: media_player.bedroom
speaker_group:
  platform: ga
  show_group_count: true
  entities:
    - entity_id: media_player.bedroom
      name: Bedroom
    - entity_id: media_player.google_in_bedroom
      name: Google in Bedroom
shortcuts:
  columns: 2
  buttons:
    - name: Rain
      type: music
      id: https://rainyday-mynoise.radioca.st/stream
    - name: Rain Mix
      type: music
      id: http://94.23.252.14:8067/stream
    - name: Ambient Nature
      type: music
      id: http://larry.torontocast.com:1540/stream/1/
    - name: Ambient Sleeping Pill
      type: music
      id: https://radio.stereoscenic.com/asp-s
    - name: Planet Ambient Radio
      type: music
      id: https://planetambi.radioca.st/stream
    - name: Zero Beat
      type: music
      id: http://62.149.196.16:8800/stream/1/
    - name: Aromatherapy
      type: music
      id: http://23.82.11.87:27028/stream
    - name: White Noise
      type: music
      id: http://96.31.83.94:8045/stream/1/
    - name: Pink Noise
      type: music
      id: http://uk1.internet-radio.com:8004/stream
    - name: Brown Noise
      type: music
      id: http://uk1.internet-radio.com:8280/stream
volume_stateless: false
replace_mute: stop
info: scroll
source: full
sound_mode: full
artwork: cover
volume_step: '1'
```
