### ISSUE TITLE
Source list stop working

### ISSUE THREAD

**Issue by cataseven** [kalkih/mini-media-player#690]
For spotify entity, when i try to select source from icon it is not assigned (Denon AVR-X2700H) and it remains blank.
I have to tap on card for reaching more info page and select source from more info page or alternatively.
```
tap_action:
  action: call-service
  service: media_player.select_source
  service_data:
    entity_id: media_player.spotify_home
    source: Denon AVR-X2700H
```
sorry for my English
