### ISSUE TITLE
idle_view is not working

### ISSUE THREAD

**Issue by meks007** [kalkih/mini-media-player#698]
Hi,

I installed Mini Media Player and so far it's working great. However I can't seem to get idle_view to work and I believe it's not due to a misconfiguration on my end:

```
type: custom:mini-media-player
entity: media_player.spotify_tablet1_ws179
artwork: full-cover
group: false
hide:
  name: true
  power: true
  volume: true
  shuffle: false
  repeat: false
  source: true
  icon: true
idle_view:
  after: 10
  when_idle: true
  when_standby: true
```

I have also tried different combinations for idle_view but no luck.

media_player.spotify_tablet1_ws179 attributes below.
It is currently 2022-09-26T12:04:30, which is 1hr 42m past media_position_updated_at but the player won't render idle_view

```
source_list: Web Player (Chrome), Family Room
volume_level: 0.17
media_content_id: spotify:track:3aFgacV2lQUD0RCJHjSN59
media_content_type: music
media_duration: 243.44
media_position: 243.44

----->>>> media_position_updated_at: 2022-09-26T10:22:08.492000+00:00 <<<<-----

media_title: 20 Something
media_artist: Pool
media_album_name: 20 Something
media_track: 1
media_playlist: Feelgood Indie
source: Family Room
shuffle: true
repeat: off
entity_picture: /api/media_player_proxy/media_player.spotify_tablet1_ws179?token=e784e6d8d692a3047af342b481ac70e447a2f840183969f30aa71e259a88061d&cache=59c88a505c0c6646
icon: mdi:spotify
friendly_name: Family Room
supported_features: 444983
```

<img width="711" alt="image" src="https://user-images.githubusercontent.com/23148641/192272017-ea96ef7f-5aa5-4ec3-a51e-d4f5c1a01793.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/23148641/192272209-55f28c54-954c-4a85-a418-00427c2aa470.png">
