### ISSUE TITLE
using Spotcat raises "Player command failed: Restriction violated, reason: UNKNOWN"

### ISSUE THREAD

**Issue by MarpleA** [kalkih/mini-media-player#708]
Hi,

I am trying to start spotcast.start via service in mini media player.

Here's my config:
```
type: custom:mini-media-player
name: tests
entity: media_player.spotify_user01
shortcuts:
  buttons:
    - name: Force Start
      type: service
      id: spotcast.start
      data:
        device_name: Echo Arbeitszimmer
        uri: spotify:playlist:37i9dQZF1DX7ZUug1ANKRP
```
this raises the following error in Home Assistant:
```
[140255592213440] http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=93d34cd2-d7cd-463b-bd7d-856da5d6fff9_amzn_1: Player command failed: Restriction violated, reason: UNKNOWN
```

However, starting this service from developer tools in HA works as expected.
```
service: spotcast.start
data:
  uri: spotify:playlist:37i9dQZF1DX7ZUug1ANKRP
  device_name: Echo Arbeitszimmer
```

Is this a bug in mini media player or did I configure something wrong?
