### ISSUE TITLE
Unable to join players to group

### ISSUE THREAD

**Issue by notrelatedtoanyone** [kalkih/mini-media-player#716]
I am unable to join players to a group, oddly enough.

I am definitely using the latest version as I only just installed it via HACS. To be sure, I also installed it manually (CLI method) and specified the version in the query parameter.

Whenever I join a player to a group, I see this error popup:
`Failed to call service media_player/join. required key not provided @ data['group_members']`

I have the following configured in the card:
```yaml
type: custom:mini-media-player
entity: media_player.living_room
hide:
  power: true
  source: true
speaker_group:
  platform: sonos
  show_group_count: true
  entities:
    - entity_id: media_player.living_room
      name: Living Room
    - entity: media_player.office
      name: Office
    - entity: media_player.bedroom
      name: Bedroom
```
