### ISSUE TITLE
Source selector doesn't render correctly in a popup

### ISSUE THREAD

**Issue by jherby2k** [kalkih/mini-media-player#740]
I'm using browser-mod to open a mini-media-player as a popup:

```yaml
      tap_action:
        action: fire-dom-event
        browser_mod:
          service: browser_mod.popup
          data:
            content:
              type: custom:mini-media-player
              entity: media_player.kitchen_speaker
              artwork: material
              hide:
                repeat: false
                shuffle: false
              tap_action:
                action: none
            timeout: 30000
            style: |
              --popup-background-color: 0;
              --popup-border-width: 0;
            card_mod:
              style:
                ha-dialog$: |
                  div.mdc-dialog div.mdc-dialog__scrim {
                    background: rgba(0, 0, 0, 0.7);
                  }
                  header.mdc-top-app-bar {
                    display: none;
                  }
```

![image](https://user-images.githubusercontent.com/9419251/221692280-b9804fcd-ca57-4637-b8a5-c74ffed15475.png)

Works great, except for the "source" dropdown renders incorrectly. Everything else seems to work fine.

![image](https://user-images.githubusercontent.com/9419251/221692347-55a0d56a-c24b-441f-982d-282003fb3df9.png)

Any chance for an easy fix?
