### ISSUE TITLE
full-cover is truncated with some media_player entries

### ISSUE THREAD

**Issue by rh8056** [kalkih/mini-media-player#747]
I'm using a universal media player to combine a few different media players from an Amplipi. In the following screenshot, all of the `mini-media-player` entries are set to full-cover. You can see that `amplipi_source_1` shows a full cover. When I look at the attributes of the `media_players` and pull out the `entity_picture`, if I paste that into a web browser, every picture is the same and none are truncated.

![image](https://user-images.githubusercontent.com/25002758/227741069-8916be38-d241-4ad2-bf89-d2abb6f1d18c.png)

I'm not sure how to help investigate, but if I open up web inspector in Safari, all three images are the same (full sized)

![image](https://user-images.githubusercontent.com/25002758/227741084-241a85e4-8f08-4e05-8c2a-671d2af046a7.png)

lovelace config:
```
    cards:
      - type: custom:mini-media-player
        entity: media_player.amplipi_source_1
        artwork: full-cover
        hide:
          power: true
          next: false
          prev: false
          play_pause: false
          play_stop: false
          progress: true
          icon: true
        name: media_player.amplipi_source_1
      - type: custom:mini-media-player
        entity: media_player.amplipi
        artwork: full-cover
        hide:
          power: true
          play_pause: false
          play_stop: false
          progress: true
          icon: true
        name: media_player.amplipi
      - type: custom:mini-media-player
        entity: media_player.kitchen_speakers
        artwork: full-cover
        hide:
          power: true
          play_pause: false
          play_stop: false
          progress: true
          icon: true
        name: media_player.kitchen_speakers
```
