### ISSUE TITLE
Need help: Anyway to give a max height?

### ISSUE THREAD

**Issue by JesperKuipers** [kalkih/mini-media-player#757]
Atm I got this 
![afbeelding](https://user-images.githubusercontent.com/44586411/235272178-1058448d-9842-4129-88a0-1ed0a8d5b517.png)
But that is way to big for my Echo show 8, so I like to make it more like this (ofc not streched, but black bars on the side to keep the artwork's aspect ratio)
![afbeelding](https://user-images.githubusercontent.com/44586411/235272389-ba974c3d-1a03-4b7b-b7be-93f58b6f9b3b.png)
So would someone tell me if this is possible? And if so how I could achieve this? (Yes I looked at the readme)

**Comment by mrUlrik** [comment]
This would be very nice. It's the only item in my dashboard that is off and it is proving to be very challenging to work around.

**Comment by Mqxx** [comment]
I also struggled with this... I used card-mod addon for HA but it seems like this only works for some reason on desktop not mobile... This should at least respect the grid options on desktop.

```yml
type: custom:mini-media-player
entity: media_player.spotify
volume_stateless: false
group: false
replace_mute: default
source: full
artwork: material
hide:
  power: true
grid_options:
  columns: 24
  rows: 2
info: scroll
card_mod:
  style:
    .: |
      :host {
        height: 100% !important;

        ha-card {
          height: 100% !important;
          
          .mmp-player {
            display: flex;
            height: 100%;
            flex-direction: column;
            justify-content: space-between;
          }
        }
      }

```
