### ISSUE TITLE
Icon state color is wrong

### ISSUE THREAD

**Issue by Hackashaq666** [kalkih/mini-media-player#759]
Hi, I am using the mini-medi-player for all of my media players and it is great!
I have noticed that the icon state color is not showing the correct color when the entity is on.
The accent color of the default or custom themes seems to be ignored, and the active icon always shows as white (amber is my theme setting). The mediaplayer "off" color is correct (blue-grey in my theme).
Is this a bug, is the card pulling in the color from incorrectly from the theme? 
(I don't see a setting for the icon "accent" color available in the additional theme variables for the mini-media-player card either.) 
Thank you!

I have set the parameter in the config to show the icon state:
```
  - entity: media_player.speaker
    type: custom:mini-media-player
    group: true
    hide:
      play_pause: true
      icon_state: false
```
