### ISSUE TITLE
Use Piper (local TTS) with media player

### ISSUE THREAD

**Issue by kksligh** [kalkih/mini-media-player#761]
Can you please add the ability to use the new local TTS service Piper? If there's a way to do this now, please let me know. I've tried playing with the yaml with no luck

**Comment by relaystar** [comment]
I'm in a similar situation.  FWIW this is what I've tried which seems to match the documentation best:

```
type: custom:mini-media-player
entity: media_player.m5_atom_echo_1
tts:
  platform: service
  data:
    service: tts.piper
    service_data:
      cache: false
      media_player_entity_id: media_player.m5_atom_echo_1
    message_field: text
```

This results in a:

"failed to call service tts/piper.  service not found"

NB, the following code works find in a script

```
service: tts.speak
data:
  cache: false
  media_player_entity_id: media_player.m5_atom_echo_1
  message: This is some test text for piper
target:
  entity_id: tts.piper
```
