### ISSUE TITLE
Feature request: Change icon color depending state.

### ISSUE THREAD

**Issue by sendorm** [kalkih/mini-media-player#77]
Would be possible to change the color of the media player icon when the power is on. Just as in `power_state`. But also the ability to change the color to whatever the user wants not just the accent color.
Thank you. 

![image](https://user-images.githubusercontent.com/29329371/52580016-7bb4bf00-2e38-11e9-99c6-473fdc76dacd.png)

**Comment by kalkih** [comment]
I could see the option `icon_state` being added, but for simplicity, I think I'll keep it to --accent-color.
You can always modify your theme if you want to change the color.

**Comment by sendorm** [comment]
Thank you :)

**Comment by kalkih** [comment]
Now available in [v1.0.1](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.1)

```yaml
# Change icon color when powered on
- type: custom:mini-media-player
  entity: media_player.example
  hide:
    icon_state: false
  ...
```
