### ISSUE TITLE
Feature request: define number of buttons on row

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-media-player#78]
Currently the shortcut item object allows a maximum of 2 buttons per row.
It would be nice if the number of buttons an a row can be configured, as the buttons are rather wide now.

**Comment by kalkih** [comment]
Next version you'll be able to set max number of buttons per row.

```yaml
- type: custom:mini-media-player
  entity: media_player.example
  shortcuts:
    columns: 4
    buttons:
      ...
```
![hyperion_8123_lovelace_4 22](https://user-images.githubusercontent.com/457678/52918124-e14ef280-32f3-11e9-8aca-fe46908b1af5.png)
