### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by MightyMilster** [kalkih/mini-media-player#80]
Hi. I am running v1.0.1 with HassIO v0.87.1. I have the TTS option enabled and when I try to use it I get...
`Failed to call service tts/undefined_say.`
For some time the entry field was pre-populated with
`Text to speak...`
and I am 99% sure that at some stage I noticed this changed to
`Say...`
Now; maybe after a prior update, it is back to
`Text to speak...`

**Comment by kalkih** [comment]
The TTS option was reworked in `v1.0.0`, listed as a [breaking change](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.0).

The new `tts` option takes an object, see: [TTS object](https://github.com/kalkih/mini-media-player#tts-object)

**Comment by MightyMilster** [comment]
Hello mate!
Oh, I read the v1.0.0 notes and with poor understanding of what an object is had this...
```
- type: "custom:mini-media-player"
  entity: media_player.mario
  icon: 'mdi:google-home'
  tts: google
```
Now I have this which works great!
```
- type: "custom:mini-media-player"
  entity: media_player.mario
  icon: 'mdi:google-home'
  tts: 
    platform: google
    enity_id: media_player.mario
```
Thanks very much! LOVE your card! Appreciate your hard work.
Best
Milster

**Comment by garywilson4** [comment]
I'mn getting the same error as the guy above and not sure what i have wrong my yaml has this 
`          - entity: media_player.everywhere
            type: custom:mini-media-player
            artwork: full-cover
            tts:
              - platform: alexa
              - entity_id: media_player.everywhere`

**Comment by loocd** [comment]
what worked for me was to remove the hyphen and space


 ```
- entity: media_player.everywhere
    type: custom:mini-media-player
    artwork: full-cover
    tts:
      platform: alexa
      entity_id: media_player.everywhere
```
