### ISSUE TITLE
Allow buttons for Sonos Speech enhance and Night sound

### ISSUE THREAD

**Issue by arsaboo** [kalkih/mini-media-player#81]
Sonos players allow toggling [speech enhance and night sound](https://www.home-assistant.io/components/sonos/#service-sonos_set_option). 

It will be great if we can have buttons to toggle these options.

**Comment by iantrich** [comment]
@arsaboo you can accomplish this with a [shortcut](https://github.com/kalkih/mini-media-player#shortcut-item-object)

**Comment by kalkih** [comment]
Yes, great suggestion @iantrich.
Please consider using the shortcut buttons.
I'm trying to avoid adding too many platform specific features.

**Comment by arsaboo** [comment]
@iantrich I went over it, but not sure how would `shortcut` be used. It only accepts `script` right now, so I can add a script to toggle the modes, but the button will not report the state (or will it?)

**Comment by arsaboo** [comment]
So, I added a script:
```yaml
  sonos_speech_toggle:
    alias: Sonos - toggle speech mode
    sequence:
        service: homeassistant.toggle
        data:
          entity_id: switch.sonos_speech_enhance
```
and added the shortcut like:
```yaml
        shortcuts:
          buttons:
            - name: Speech Enhance
              icon: mdi:comment-check-outline
              type: script
              id: script.sonos_speech_toggle
```
The button shows, but it does not report the current state.
