### ISSUE TITLE
(Heos) Group Management - activating an entity disables all others

### ISSUE THREAD

**Issue by 4s1** [kalkih/mini-media-player#830]
(Heos) Grouping is acting strange. 

Whenever I toggle on an entity in group management, which would have 2 entries activated, it toggles off all other entities than the one activated. So I'm not able to activate more than one additional player, other than use group all and deselect unneeded players.

https://github.com/kalkih/mini-media-player/assets/15968622/0fa432b6-9def-4ab1-bb8d-36699cbadb86

 ```yaml
card:
  type: custom:mini-media-player
  entity: media_player.kuche
  group: true
  volume_stateless: false
  artwork: material
  sound_mode: full
  speaker_group:
    platfom: heos
    show_group_count: true
    expanded: true
    entities:
      - entity_id: media_player.badezimmer
        name: Badezimmer
      - entity_id: media_player.schlafzimmer
        name: Schlafzimmer
      - entity_id: media_player.buro
        name: Büro

```

Fresh installation 
- Homeassistant 2024.2.1
- HAOS 11.5
- HACS 1.34.0
- Mini Player 1.16.9
