### ISSUE TITLE
Highlight currently active item in list dropdown

### ISSUE THREAD

**Issue by appel** [kalkih/mini-media-player#835]
Forgive me if this has been asked and answered before. I searched but could not find it. I'm currently using shortcuts in list form. I assumed when selecting a shortcut from the list dropdown that this shortcut would be highlighted/selected but it appears that's not the case. Is there any way I can make this happen?

My config:

```
type: custom:mini-media-player
entity: media_player.downstairs
shortcuts:
  label: Pick a stream...
  list:
    - type: script
      name: SomaFm Folk Forward
      id: script.media_somafm_folk_fwd
    - type: script
      name: SomaFm 7" Soul
      id: script.radio_somafm_seven_inch_soul
```

![image](https://github.com/kalkih/mini-media-player/assets/61596/dccf873a-8593-41de-adf9-4a9bc11e8eef)

Thanks in advance!
