### ISSUE TITLE
[Feature Request] List object to choose one of my Echos

### ISSUE THREAD

**Issue by Obicom** [kalkih/mini-media-player#85]
First of all thank you for your great work. I have a Alexa i every room and it would be awesome if I could choose my device from a list in one mini media player card. Now I have to create a mini card for every device. Would this be possible?

To additional questions:  
1. TTS to all alexas doesn't work with "entity_id: all" What did I wrong?
2. I have three scripts to start my favorite internet radio channel via tunein with the alexa media player. Now I create three buttons and as source I use script. This works but in the script I have also to specify the entity (e.g. media_player.kitchen). Is there a other easy way to start a internet radio channel via tunein?

**Comment by kalkih** [comment]
> First of all thank you for your great work. I have a Alexa i every room and it would be awesome if I could choose my device from a list in one mini media player card. Now I have to create a mini card for every device. Would this be possible?

Thanks!

You could achieve this by setting up an [input select](https://www.home-assistant.io/components/input_select/), and then use [conditional cards](https://www.home-assistant.io/lovelace/conditional/) to render the entity selected in the input select. There might be a more elegant solution than using conditional cards, since you would have to set up quite a few, but I guess it's mostly copy-paste.

1. It's possible that it doesn't work in the [custom alexa component](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639), have you tried doing it manually to see if it works?

2. I've never used the custom alexa component or tunein for that matter, but if it does support [media_player.play_media](https://www.home-assistant.io/components/media_player/#service-media_playerplay_media) you could possibly skip the script and set `type: music` & `id: tunein-uri`. diectly in the shortcut.

**Comment by Obicom** [comment]
Thank you for the very quick response ...

`You could achieve this by setting up an [input select](https://www.home-assistant.io/components/input_select/), and then use [conditional cards](https://www.home-assistant.io/lovelace/conditional/) to render the entity selected in the input select. There might be a more elegant solution than using conditional cards, since you would have to set up quite a few, but I guess it's mostly copy-paste.` 

Sorry that I am so blond but I have no idea how. Do you have an example?

> 1. It's possible that it doesn't work in the [custom alexa component](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639), have you tried doing it manually to see if it works?

No it doesn't work 

> 2\. I've never used the custom alexa component or tunein for that matter, but if it does support [media_player.play_media](https://www.home-assistant.io/components/media_player/#service-media_playerplay_media) you could possibly skip the script and set `type: music` & `id: tunein-uri`. diectly in the shortcut.

I will try

**Comment by kalkih** [comment]
> Sorry that I am so blond but I have no idea how. Do you have an example?

Don't have an example, but it should be quite easy.

1. Set up an input select, with one option for each echo you got.
```yaml
input_select:
  selected_echo:
    name: Echo
    options:
      - First Echo
      - Second Echo
      - Another one
    initial: First Echo
    icon: mdi:music
```
2. Put the input select you created in an entities card.
```yaml
- type: entities
  entities:
    - input_select.selected_echo
```
3. Create one conditional card for each echo you got, the conditions should be to check if the input select state matches the name of the echo. Put it inside the same entities card as the input select or anywhere you want.
```yaml
# conditional card example (one for each echo)
type: conditional
conditions:
  - entity: input_select.selected_echo
    state: "First Echo"
card:
  - type: custom:mini-media-player
    entity: media_player.first_echo
    ...
```

> No it doesn't work

Okay, nothing I can do then, sorry.

> here a example script:

If that script works, you should be able to put this right in the mini-media-player card:
```yaml
...
buttons:
  - icon: mdi:cat
    type: TUNEIN
    id: 1live überall
  ...
```
