### ISSUE TITLE
Docs for Shortcut buttons for spotify not working

### ISSUE THREAD

**Issue by jimmyeao** [kalkih/mini-media-player#850]
I am trying to add some shortcut buttons like referenced in the docs:

```
    buttons:
      # Start predefined playlist
      - icon: mdi:cat
        type: playlist
        id: spotify:user:XXXXXXX:playlist:37i9dQZF1DZ06evO2O09Hg # Where XXXXXXX is your User ID
```
However, this gives an error
`Failed to call service media_player/play_media. required key not provided @ data['media_content_id']`

This is my (obfuscated) card yaml:
```
card:
  show_header_toggle: false
  title: Spotify Players
  type: entities
filter:
  exclude:
    - state: 'off'
    - state: unavailable
  include:
    - domain: media_player
      entity_id: '*spotify*'
      options:
        type: custom:mini-media-player
        artwork: cover
        shortcuts:
          buttons:
            - name: Best AnjunaDeep
              type: spotify:user:XXXXXX:playlist:XXXXXXXXXXXXXX
type: custom:auto-entities
layout_options:
  grid_columns: 4
  grid_rows: 5
```
Which allows me to select the media player; the button should then play the playlist on the selected player
