### ISSUE TITLE
Possible to hide shortcut buttons based on conditions?

### ISSUE THREAD

**Issue by 0xskynet** [kalkih/mini-media-player#864]
Trying to hide the buttons based on a state (eg.  `states.media_player.my_rest_2nd_gen_media_player.state == 'playing'` ). Possible with mini media player ?

```
type: custom:mini-media-player
entity: media_player.my_rest_2nd_gen_media_player
group: false
volume_stateless: false
toggle_power: false
artwork: cover-fit
source: full
power_buttons:
  power:
    type: script
    id: script.rest_media_stop
shortcuts:
  buttons:
    - icon: mdi:stop
      type: script
      id: script.rest_media_stop
    - icon: mdi:play
      type: script
      id: script.rest_set_sound_mode
      data:
        sound_mode: WhiteNoise
```
