### ISSUE TITLE
[Feature Request] Alignment of button text

### ISSUE THREAD

**Issue by schneekluth** [kalkih/mini-media-player#87]
Please add an option in the "Shortcuts object" section for text alignment, e.g.:

```YAML
  ...
  shortcuts:
    columns: 3
    text_align: left/center
    buttons:
      - name: Deepmix Moscow
        type: playlist
        id: 1
      - name: Low-Fidelity
        type: playlist
        id: 2
      - name: 'Beats, Beats!'
        type: playlist
        id: 3
  ...
```
That way those buttons would look much nicer and better formatted:

![mmp_issue](https://user-images.githubusercontent.com/5740913/53119914-dd6bdc00-3550-11e9-8750-1f440b75c0a9.png)
