### ISSUE TITLE
Sonos group volume sync player volume offset

### ISSUE THREAD

**Issue by ronschaeffer** [kalkih/mini-media-player#88]
First off, great work! This is a fantastic card, just what I've been wishing for to control Sonos, and well worth the move to Lovelace on its own.

A feature request: Following on from the Sonos group volume sync added in response to #48, please add the option to set a volume offset for individual players. Something like:

`sync_volume_offset: [value]`

A card configuration might look something like:

```
  - type: 'custom:mini-media-player'
    entity: media_player.dining_room
    hide:
      icon: true
      power: true
      source: false
    artwork: cover
    sonos:
      expanded: true
      sync_volume: false
      entities:
        - entity_id: media_player.kitchen
          name: Kitchen
          sync_volume_offset: 5                              [5 levels louder than the group master]
        - entity_id: media_player.living_room
          name: Living Room
          sync_volume_offset: -3                             [3 levels quieter than the group master]
        - entity_id: media_player.bedroom
          name: Bedroom                                 [No offset specified, so same volume as group master]
```

A use case example:  I have a number of regular Sonos speakers plus one Connect Amp connected to a pair of non-amplified speakers (Kitchen). At any given volume level (for example, level 10) the Kitchen speakers sound quieter than the speakers in the rest of the house. To compensate, I set the Kitchen speakers to 5 volume levels higher than the speakers in the rest of the house. Once I've done that, the volume slider for the group in the Sonos app maintains the relative volume difference between the speakers.
