### ISSUE TITLE
[render bug] doesn't split in 2 lines even if there is enough space

### ISSUE THREAD

**Issue by lollilol** [kalkih/mini-media-player#885]
when setting the name to a space it won't be displayed. mini-media-player doesn't know that and continues to display only 1 line of text, even when there is enough space for displaying 2 lines.

![Image](https://github.com/user-attachments/assets/7dff7365-36cd-4abf-add1-50b23f73cfcd)

```yaml
type: custom:mini-media-player
name: " "
entity: media_player.spotify_lollilol
group: false
volume_stateless: false
toggle_power: true
hide:
  progress: true
  volume: true
  power: true
  source: true
  runtime: false
  runtime_remaining: false
visibility:
  - condition: state
    entity: media_player.spotify_lollilol
    state_not: idle
  - condition: state
    entity: media_player.spotify_lollilol
    state_not: unavailable
artwork: cover
```
