### ISSUE TITLE
Linkplay devices and group management buttons

### ISSUE THREAD

**Issue by Daybreak9696** [kalkih/mini-media-player#892]
Hi,
I recently switched from the now unsupported HACS Linkplay integration to the official Home Assistant one. I have 3 Arylic devices that I control with the HACS Mini Media Player card. I saw there was another thread on the Linkplay integration moving to core HA, but it didn't seem to address this specific issue. 

Before the switch, they were all working fine - I could group and ungroup them with the slider switch that shows up when I clicked the group icon in the top right of the card. I previously had the "platform" configuration set to platform: linkplay (now it is platform: media_player). 

After the switch, I updated the entities to the correct new names and changed the group platform. Now when I group one speaker with another, it works, but the group selection area of the card becomes grayed out and unusable. I need to navigate to the other mini media player card that I grouped and select "Leave" instead of simply clicking the slider from the first card. 

Thanks in advance for your help! 

```
type: custom:mini-media-player
entity: media_player.kitchen
hide:
  power: true
shortcuts:
  columns: 2
  buttons:
    - icon: mdi:spotify
      name: Alt Now (Stu)
      type: script
      id: script.spotify_cast_kitchen_alt_now_stuart
    - icon: mdi:spotify
      name: Chill Mix (Stu)
      type: script
      id: script.spotify_cast_kitchen_chill_mix_stuart
    - icon: mdi:spotify
      name: Alt Now (Abbi)
      type: script
      id: script.spotify_cast_kitchen_alt_now_abbi
    - icon: mdi:spotify
      name: Elli's Alt (Abbi)
      type: script
      id: script.spotify_cast_kitchen_elli_s_alternative_abbi
artwork: material
speaker_group:
  platform: media_player
  show_group_count: true
  entities:
    - entity_id: media_player.kitchen
      name: Kitchen
    - entity_id: media_player.living_room
      name: Living Room
    - entity_id: media_player.backyard
      name: Backyard
  sync_volume: false
visibility:
  - condition: numeric_state
    entity: input_number.statusword_kitchen_arylic
    above: -1
```
In this picture, I clicked the slider for Living Room and the grouping was successful, but now the Group Management sliders are grayed out and I'm unable to use them. 
![Image](https://github.com/user-attachments/assets/653a412f-37a7-4720-99fe-85b229068a6b)
