### ISSUE TITLE
[Feature Request] ability to add group as entity (like: group.media_players_upstairs)

### ISSUE THREAD

**Issue by backcountrymountains** [kalkih/mini-media-player#95]
So I really like this card, tons of options and well done.

I manually stream to a HA group of chromecasts (group.media_players_upstairs), and it would be super awesome if I could add the group to the card with a button so I can click and have it simultaneously stream to the group. I tried adding it to the card but it threw an error because 'group' isn't from the 'media_player' domain.

the following script works to stream to a group of chromecasts:
  ```
play_stream:
    alias: play stream on group
    sequence:
      service: media_player.play_media
      data:
        entity_id: group.media_player_upstairs
        media_content_type: music
      data_template:
        media_content_id: "super cool stream here"
```
So I'm hoping the domain restriction can be lifted on the card? or something? I have no idea what I'm doing.

Anyway, just wanted to throw that out there.

Thanks for the great card!
