### ISSUE TITLE
can't get tts working

### ISSUE THREAD

**Issue by garywilson4** [kalkih/mini-media-player#98]
I'm getting the same error as MightyMilster quoted in an earlier post `Failed to call service tts/undefined_say. `and not sure what i have wrong, my yaml has this 
```
 - entity: media_player.everywhere
    type: custom:mini-media-player
    artwork: full-cover
    tts:
      - platform: alexa
      - entity_id: media_player.everywhere
```

is there something i have missed maybe? it used to work fine till i updated

**Comment by kalkih** [comment]
Your config is slightly incorrect; the tts option is an object of strings not an object of arrays.

Also, the slexa tts does not support `entity_id` as stated [here](https://github.com/kalkih/mini-media-player#tts-object), and providing this option will make the tts fail. This is getting fixed next release, so the unsupported option will simply be ignored instead of messing up the service call. 881e06728fd8e43021b44548a7bd3ee08e2b572e

This config should work:
```yaml
 - entity: media_player.everywhere
   type: custom:mini-media-player
   artwork: full-cover
   tts:
     platform: alexa
```

I suppose `media_player.everywhere` is an entity from the "alexa as media player" component?
